//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
//using BPA.Framework.XML;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="CLMBCNCUSoap", Namespace="HTTP://SHADOW.CONSECO.COM/CLMSYSTEM/CLMBCNCU")]
public partial class CLMBCNCU : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private zAuthPwd zAuthPwdValueField;
    
    private System.Threading.SendOrPostCallback CallCLMBCNCUOperationCompleted;
    
    /// <remarks/>
    public CLMBCNCU(string URL) {
        //this.Url = "http://MFWEBT.CONSECO.COM:6111/CLMSYSTEM/CLMBCNCU.zws";
       this.Url = URL;
    }
    
    public zAuthPwd zAuthPwdValue {
        get {
            return this.zAuthPwdValueField;
        }
        set {
            this.zAuthPwdValueField = value;
        }
    }
    
    /// <remarks/>
    public event CallCLMBCNCUCompletedEventHandler CallCLMBCNCUCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("zAuthPwdValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HTTP://SHADOW.CONSECO.COM/CLMSYSTEM/CLMBCNCU/CLMBCNCU", RequestElementName="CLMBCNCU", RequestNamespace="HTTP://SHADOW.CONSECO.COM/CLMSYSTEM/CLMBCNCU", ResponseElementName="CLMBCNCUResponse", ResponseNamespace="HTTP://SHADOW.CONSECO.COM/CLMSYSTEM/CLMBCNCU", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("CLMBCNCUResult")]
    public Clmbcncu_area CallCLMBCNCU(Clmbcncu_input CLMBCNCUInput) 
    {

        object[] results = this.Invoke("CallCLMBCNCU", new object[] {
                    CLMBCNCUInput});
        return ((Clmbcncu_area)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCallCLMBCNCU(Clmbcncu_input CLMBCNCUInput, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CallCLMBCNCU", new object[] {
                    CLMBCNCUInput}, callback, asyncState);
    }
    
    /// <remarks/>
    public Clmbcncu_area EndCallCLMBCNCU(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Clmbcncu_area)(results[0]));
    }
    
    /// <remarks/>
    public void CallCLMBCNCUAsync(Clmbcncu_input CLMBCNCUInput) {
        this.CallCLMBCNCUAsync(CLMBCNCUInput, null);
    }
    
    /// <remarks/>
    public void CallCLMBCNCUAsync(Clmbcncu_input CLMBCNCUInput, object userState) {
        if ((this.CallCLMBCNCUOperationCompleted == null)) {
            this.CallCLMBCNCUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallCLMBCNCUOperationCompleted);
        }
        this.InvokeAsync("CallCLMBCNCU", new object[] {
                    CLMBCNCUInput}, this.CallCLMBCNCUOperationCompleted, userState);
    }
    
    private void OnCallCLMBCNCUOperationCompleted(object arg) {
        if ((this.CallCLMBCNCUCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CallCLMBCNCUCompleted(this, new CallCLMBCNCUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="HTTP://SHADOW.CONSECO.COM/CLMSYSTEM/CLMBCNCU")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/CLMSYSTEM/CLMBCNCU", IsNullable=false)]
public partial class zAuthPwd : System.Web.Services.Protocols.SoapHeader {
    
    private string userIdField;
    
    private string passwordField;
    
    /// <remarks/>
    public string UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/CLMSYSTEM/CLMBCNCU")]
public partial class Clmbcncu_areaClmbcncu_outputClmbcncu_srt_array {
    
    private string clmbcncu_srt_planField;
    
    private string clmbcncu_srt_xrefField;
    
    private string clmbcncu_srt_cdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_srt_plan {
        get {
            return this.clmbcncu_srt_planField;
        }
        set {
            this.clmbcncu_srt_planField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_srt_xref {
        get {
            return this.clmbcncu_srt_xrefField;
        }
        set {
            this.clmbcncu_srt_xrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_srt_cd {
        get {
            return this.clmbcncu_srt_cdField;
        }
        set {
            this.clmbcncu_srt_cdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/CLMSYSTEM/CLMBCNCU")]
public partial class Clmbcncu_areaClmbcncu_output {
    
    private string clmbcncu_bundle_nbrField;
    
    private string clmbcncu_xref_polField;
    
    private string clmbcncu_chk_digField;
    
    private string clmbcncu_nameField;
    
    private string clmbcncu_addr1Field;
    
    private string clmbcncu_addr2Field;
    
    private string clmbcncu_city_st_zipField;
    
    private string clmbcncu_issue_dtField;
    
    private string clmbcncu_paid_to_dtField;
    
    private string clmbcncu_paid_to_msgField;
    
    private string clmbcncu_exp_payField;
    
    private string clmbcncu_rop_cashField;
    
    private System.Nullable<short> clmbcncu_srt_cntField;
    
    private Clmbcncu_areaClmbcncu_outputClmbcncu_srt_array[] clmbcncu_srt_arrayField;
    
    private string clmbcncu_related_pol1Field;
    
    private string clmbcncu_related_pol2Field;
    
    private string clmbcncu_related_pol3Field;
    
    private string clmbcncu_msgField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_bundle_nbr {
        get {
            return this.clmbcncu_bundle_nbrField;
        }
        set {
            this.clmbcncu_bundle_nbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_xref_pol {
        get {
            return this.clmbcncu_xref_polField;
        }
        set {
            this.clmbcncu_xref_polField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_chk_dig {
        get {
            return this.clmbcncu_chk_digField;
        }
        set {
            this.clmbcncu_chk_digField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_name {
        get {
            return this.clmbcncu_nameField;
        }
        set {
            this.clmbcncu_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_addr1 {
        get {
            return this.clmbcncu_addr1Field;
        }
        set {
            this.clmbcncu_addr1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_addr2 {
        get {
            return this.clmbcncu_addr2Field;
        }
        set {
            this.clmbcncu_addr2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_city_st_zip {
        get {
            return this.clmbcncu_city_st_zipField;
        }
        set {
            this.clmbcncu_city_st_zipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_issue_dt {
        get {
            return this.clmbcncu_issue_dtField;
        }
        set {
            this.clmbcncu_issue_dtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_paid_to_dt {
        get {
            return this.clmbcncu_paid_to_dtField;
        }
        set {
            this.clmbcncu_paid_to_dtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_paid_to_msg {
        get {
            return this.clmbcncu_paid_to_msgField;
        }
        set {
            this.clmbcncu_paid_to_msgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_exp_pay {
        get {
            return this.clmbcncu_exp_payField;
        }
        set {
            this.clmbcncu_exp_payField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_rop_cash {
        get {
            return this.clmbcncu_rop_cashField;
        }
        set {
            this.clmbcncu_rop_cashField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> Clmbcncu_srt_cnt {
        get {
            return this.clmbcncu_srt_cntField;
        }
        set {
            this.clmbcncu_srt_cntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Clmbcncu_srt_array", IsNullable=true)]
    public Clmbcncu_areaClmbcncu_outputClmbcncu_srt_array[] Clmbcncu_srt_array {
        get {
            return this.clmbcncu_srt_arrayField;
        }
        set {
            this.clmbcncu_srt_arrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_related_pol1 {
        get {
            return this.clmbcncu_related_pol1Field;
        }
        set {
            this.clmbcncu_related_pol1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_related_pol2 {
        get {
            return this.clmbcncu_related_pol2Field;
        }
        set {
            this.clmbcncu_related_pol2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_related_pol3 {
        get {
            return this.clmbcncu_related_pol3Field;
        }
        set {
            this.clmbcncu_related_pol3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_msg {
        get {
            return this.clmbcncu_msgField;
        }
        set {
            this.clmbcncu_msgField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/CLMSYSTEM/CLMBCNCU")]
public partial class Clmbcncu_areaClmbcncu_msgs {
    
    private string clmbcncu_msg_lvlField;
    
    private string clmbcncu_msg_textField;
    
    private string clmbcncu_sys_textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_msg_lvl {
        get {
            return this.clmbcncu_msg_lvlField;
        }
        set {
            this.clmbcncu_msg_lvlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_msg_text {
        get {
            return this.clmbcncu_msg_textField;
        }
        set {
            this.clmbcncu_msg_textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_sys_text {
        get {
            return this.clmbcncu_sys_textField;
        }
        set {
            this.clmbcncu_sys_textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/CLMSYSTEM/CLMBCNCU")]
public partial class Clmbcncu_areaClmbcncu_input {
    
    private string clmbcncu_typeField;
    
    private string clmbcncu_systemField;
    
    private string clmbcncu_companyField;
    
    private string clmbcncu_idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_type {
        get {
            return this.clmbcncu_typeField;
        }
        set {
            this.clmbcncu_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_system {
        get {
            return this.clmbcncu_systemField;
        }
        set {
            this.clmbcncu_systemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_company {
        get {
            return this.clmbcncu_companyField;
        }
        set {
            this.clmbcncu_companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_id {
        get {
            return this.clmbcncu_idField;
        }
        set {
            this.clmbcncu_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/CLMSYSTEM/CLMBCNCU")]
public partial class Clmbcncu_area {
    
    private Clmbcncu_areaClmbcncu_input clmbcncu_inputField;
    
    private Clmbcncu_areaClmbcncu_msgs clmbcncu_msgsField;
    
    private Clmbcncu_areaClmbcncu_output clmbcncu_outputField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Clmbcncu_areaClmbcncu_input Clmbcncu_input {
        get {
            return this.clmbcncu_inputField;
        }
        set {
            this.clmbcncu_inputField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Clmbcncu_areaClmbcncu_msgs Clmbcncu_msgs {
        get {
            return this.clmbcncu_msgsField;
        }
        set {
            this.clmbcncu_msgsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Clmbcncu_areaClmbcncu_output Clmbcncu_output {
        get {
            return this.clmbcncu_outputField;
        }
        set {
            this.clmbcncu_outputField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/CLMSYSTEM/CLMBCNCU")]
public partial class Clmbcncu_input {
    
    private string clmbcncu_typeField;
    
    private string clmbcncu_systemField;
    
    private string clmbcncu_companyField;
    
    private string clmbcncu_idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_type {
        get {
            return this.clmbcncu_typeField;
        }
        set {
            this.clmbcncu_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_system {
        get {
            return this.clmbcncu_systemField;
        }
        set {
            this.clmbcncu_systemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_company {
        get {
            return this.clmbcncu_companyField;
        }
        set {
            this.clmbcncu_companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Clmbcncu_id {
        get {
            return this.clmbcncu_idField;
        }
        set {
            this.clmbcncu_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void CallCLMBCNCUCompletedEventHandler(object sender, CallCLMBCNCUCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CallCLMBCNCUCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CallCLMBCNCUCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Clmbcncu_area Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Clmbcncu_area)(this.results[0]));
        }
    }
}
