//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="QSRCH2Soap", Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QSRCH2")]
public partial class QSRCH2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CallQSRCH2OperationCompleted;
    
    /// <remarks/>
    public QSRCH2(string URL) {
        //this.Url = "http://MFWEBT.CONSECO.COM:6111/QSEARCH/QSRCH2.zws";
        this.Url = URL;
    }
    
    /// <remarks/>
    public event CallQSRCH2CompletedEventHandler CallQSRCH2Completed;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HTTP://SHADOW.CONSECO.COM/QSEARCH/QSRCH2/QSRCH2", RequestElementName="QSRCH2", RequestNamespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QSRCH2", ResponseElementName="QSRCH2Response", ResponseNamespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QSRCH2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("QSRCH2Result")]
    public Qsrch2_area CallQSRCH2(Qsrch2_input QSRCH2Input) {
        object[] results = this.Invoke("CallQSRCH2", new object[] {
                    QSRCH2Input});
        return ((Qsrch2_area)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCallQSRCH2(Qsrch2_input QSRCH2Input, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CallQSRCH2", new object[] {
                    QSRCH2Input}, callback, asyncState);
    }
    
    /// <remarks/>
    public Qsrch2_area EndCallQSRCH2(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Qsrch2_area)(results[0]));
    }
    
    /// <remarks/>
    public void CallQSRCH2Async(Qsrch2_input QSRCH2Input) {
        this.CallQSRCH2Async(QSRCH2Input, null);
    }
    
    /// <remarks/>
    public void CallQSRCH2Async(Qsrch2_input QSRCH2Input, object userState) {
        if ((this.CallQSRCH2OperationCompleted == null)) {
            this.CallQSRCH2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallQSRCH2OperationCompleted);
        }
        this.InvokeAsync("CallQSRCH2", new object[] {
                    QSRCH2Input}, this.CallQSRCH2OperationCompleted, userState);
    }
    
    private void OnCallQSRCH2OperationCompleted(object arg) {
        if ((this.CallQSRCH2Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CallQSRCH2Completed(this, new CallQSRCH2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QSRCH2")]
public partial class Qsrch2_input {
    
    private string qsrch2_source_sysField;
    
    private string qsrch2_in_nameField;
    
    private string qsrch2_in_idField;
    
    private string qsrch2_in_area_cdField;
    
    private string qsrch2_in_phoneField;
    
    private string qsrch2_in_ssnField;
    
    private string qsrch2_in_zipField;
    
    private string qsrch2_in_birthField;
    
    private string qsrch2_in_sysField;
    
    private string qsrch2_in_cmpField;
    
    private string qsrch2_in_name_typeField;
    
    private string qsrch2_in_lobField;
    
    private string qsrch2_in_stateField;
    
    private string qsrch2_eofField;
    
    private string qsrch2_more1Field;
    
    private string qsrch2_more2Field;
    
    private string qsrch2_more3Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_source_sys {
        get {
            return this.qsrch2_source_sysField;
        }
        set {
            this.qsrch2_source_sysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_name {
        get {
            return this.qsrch2_in_nameField;
        }
        set {
            this.qsrch2_in_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_id {
        get {
            return this.qsrch2_in_idField;
        }
        set {
            this.qsrch2_in_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_area_cd {
        get {
            return this.qsrch2_in_area_cdField;
        }
        set {
            this.qsrch2_in_area_cdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_phone {
        get {
            return this.qsrch2_in_phoneField;
        }
        set {
            this.qsrch2_in_phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_ssn {
        get {
            return this.qsrch2_in_ssnField;
        }
        set {
            this.qsrch2_in_ssnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_zip {
        get {
            return this.qsrch2_in_zipField;
        }
        set {
            this.qsrch2_in_zipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_birth {
        get {
            return this.qsrch2_in_birthField;
        }
        set {
            this.qsrch2_in_birthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_sys {
        get {
            return this.qsrch2_in_sysField;
        }
        set {
            this.qsrch2_in_sysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_cmp {
        get {
            return this.qsrch2_in_cmpField;
        }
        set {
            this.qsrch2_in_cmpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_name_type {
        get {
            return this.qsrch2_in_name_typeField;
        }
        set {
            this.qsrch2_in_name_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_lob {
        get {
            return this.qsrch2_in_lobField;
        }
        set {
            this.qsrch2_in_lobField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_state {
        get {
            return this.qsrch2_in_stateField;
        }
        set {
            this.qsrch2_in_stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_eof {
        get {
            return this.qsrch2_eofField;
        }
        set {
            this.qsrch2_eofField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_more1 {
        get {
            return this.qsrch2_more1Field;
        }
        set {
            this.qsrch2_more1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_more2 {
        get {
            return this.qsrch2_more2Field;
        }
        set {
            this.qsrch2_more2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_more3 {
        get {
            return this.qsrch2_more3Field;
        }
        set {
            this.qsrch2_more3Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QSRCH2")]
public partial class Qsrch2_areaQsrch2_outputQsrch2_array {
    
    private string qsrch2_name_typeField;
    
    private string qsrch2_sysField;
    
    private string qsrch2_cmpField;
    
    private string qsrch2_idField;
    
    private string qsrch2_seqField;
    
    private string qsrch2_cust_idField;
    
    private string qsrch2_line_of_busField;
    
    private string qsrch2_productField;
    
    private string qsrch2_issue_countryField;
    
    private string qsrch2_issue_stateField;
    
    private string qsrch2_issue_dateField;
    
    private string qsrch2_termination_dateField;
    
    private string qsrch2_statusField;
    
    private string qsrch2_status_reasonField;
    
    private string qsrch2_base_plan_codeField;
    
    private string qsrch2_group_numberField;
    
    private string qsrch2_nameField;
    
    private string qsrch2_addr_line1Field;
    
    private string qsrch2_addr_line2Field;
    
    private string qsrch2_addr_line3Field;
    
    private string qsrch2_addr_line4Field;
    
    private string qsrch2_addr_cityField;
    
    private string qsrch2_addr_stateField;
    
    private string qsrch2_addr_zipField;
    
    private string qsrch2_addr_zip4Field;
    
    private string qsrch2_addr_countryField;
    
    private string qsrch2_area_codeField;
    
    private string qsrch2_phoneField;
    
    private string qsrch2_phone_extField;
    
    private string qsrch2_birthField;
    
    private string qsrch2_ssnField;
    
    private string qsrch2_corp_tax_idField;
    
    private string qsrch2_medicare_idField;
    
    private string qsrch2_sexField;
    
    private string qsrch2_relationshipField;
    
    private string qsrch2_person_statusField;
    
    private string qsrch2_person_status_reasonField;
    
    private string qsrch2_last_activityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_name_type {
        get {
            return this.qsrch2_name_typeField;
        }
        set {
            this.qsrch2_name_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_sys {
        get {
            return this.qsrch2_sysField;
        }
        set {
            this.qsrch2_sysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_cmp {
        get {
            return this.qsrch2_cmpField;
        }
        set {
            this.qsrch2_cmpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_id {
        get {
            return this.qsrch2_idField;
        }
        set {
            this.qsrch2_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_seq {
        get {
            return this.qsrch2_seqField;
        }
        set {
            this.qsrch2_seqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_cust_id {
        get {
            return this.qsrch2_cust_idField;
        }
        set {
            this.qsrch2_cust_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_line_of_bus {
        get {
            return this.qsrch2_line_of_busField;
        }
        set {
            this.qsrch2_line_of_busField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_product {
        get {
            return this.qsrch2_productField;
        }
        set {
            this.qsrch2_productField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_issue_country {
        get {
            return this.qsrch2_issue_countryField;
        }
        set {
            this.qsrch2_issue_countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_issue_state {
        get {
            return this.qsrch2_issue_stateField;
        }
        set {
            this.qsrch2_issue_stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_issue_date {
        get {
            return this.qsrch2_issue_dateField;
        }
        set {
            this.qsrch2_issue_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_termination_date {
        get {
            return this.qsrch2_termination_dateField;
        }
        set {
            this.qsrch2_termination_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_status {
        get {
            return this.qsrch2_statusField;
        }
        set {
            this.qsrch2_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_status_reason {
        get {
            return this.qsrch2_status_reasonField;
        }
        set {
            this.qsrch2_status_reasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_base_plan_code {
        get {
            return this.qsrch2_base_plan_codeField;
        }
        set {
            this.qsrch2_base_plan_codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_group_number {
        get {
            return this.qsrch2_group_numberField;
        }
        set {
            this.qsrch2_group_numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_name {
        get {
            return this.qsrch2_nameField;
        }
        set {
            this.qsrch2_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_addr_line1 {
        get {
            return this.qsrch2_addr_line1Field;
        }
        set {
            this.qsrch2_addr_line1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_addr_line2 {
        get {
            return this.qsrch2_addr_line2Field;
        }
        set {
            this.qsrch2_addr_line2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_addr_line3 {
        get {
            return this.qsrch2_addr_line3Field;
        }
        set {
            this.qsrch2_addr_line3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_addr_line4 {
        get {
            return this.qsrch2_addr_line4Field;
        }
        set {
            this.qsrch2_addr_line4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_addr_city {
        get {
            return this.qsrch2_addr_cityField;
        }
        set {
            this.qsrch2_addr_cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_addr_state {
        get {
            return this.qsrch2_addr_stateField;
        }
        set {
            this.qsrch2_addr_stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_addr_zip {
        get {
            return this.qsrch2_addr_zipField;
        }
        set {
            this.qsrch2_addr_zipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_addr_zip4 {
        get {
            return this.qsrch2_addr_zip4Field;
        }
        set {
            this.qsrch2_addr_zip4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_addr_country {
        get {
            return this.qsrch2_addr_countryField;
        }
        set {
            this.qsrch2_addr_countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_area_code {
        get {
            return this.qsrch2_area_codeField;
        }
        set {
            this.qsrch2_area_codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_phone {
        get {
            return this.qsrch2_phoneField;
        }
        set {
            this.qsrch2_phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_phone_ext {
        get {
            return this.qsrch2_phone_extField;
        }
        set {
            this.qsrch2_phone_extField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_birth {
        get {
            return this.qsrch2_birthField;
        }
        set {
            this.qsrch2_birthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_ssn {
        get {
            return this.qsrch2_ssnField;
        }
        set {
            this.qsrch2_ssnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_corp_tax_id {
        get {
            return this.qsrch2_corp_tax_idField;
        }
        set {
            this.qsrch2_corp_tax_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_medicare_id {
        get {
            return this.qsrch2_medicare_idField;
        }
        set {
            this.qsrch2_medicare_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_sex {
        get {
            return this.qsrch2_sexField;
        }
        set {
            this.qsrch2_sexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_relationship {
        get {
            return this.qsrch2_relationshipField;
        }
        set {
            this.qsrch2_relationshipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_person_status {
        get {
            return this.qsrch2_person_statusField;
        }
        set {
            this.qsrch2_person_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_person_status_reason {
        get {
            return this.qsrch2_person_status_reasonField;
        }
        set {
            this.qsrch2_person_status_reasonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_last_activity {
        get {
            return this.qsrch2_last_activityField;
        }
        set {
            this.qsrch2_last_activityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QSRCH2")]
public partial class Qsrch2_areaQsrch2_output {
    
    private string qsrch2_resultField;
    
    private System.Nullable<short> qsrch2_cntField;
    
    private bool qsrch2_cntFieldSpecified;
    
    private Qsrch2_areaQsrch2_outputQsrch2_array[] qsrch2_arrayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_result {
        get {
            return this.qsrch2_resultField;
        }
        set {
            this.qsrch2_resultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> Qsrch2_cnt {
        get {
            return this.qsrch2_cntField;
        }
        set {
            this.qsrch2_cntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Qsrch2_cntSpecified {
        get {
            return this.qsrch2_cntFieldSpecified;
        }
        set {
            this.qsrch2_cntFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Qsrch2_array", IsNullable=true)]
    public Qsrch2_areaQsrch2_outputQsrch2_array[] Qsrch2_array {
        get {
            return this.qsrch2_arrayField;
        }
        set {
            this.qsrch2_arrayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QSRCH2")]
public partial class Qsrch2_areaQsrch2_msgs {
    
    private string qsrch2_msg_lvlField;
    
    private string qsrch2_msg_textField;
    
    private string qsrch2_sys_textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_msg_lvl {
        get {
            return this.qsrch2_msg_lvlField;
        }
        set {
            this.qsrch2_msg_lvlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_msg_text {
        get {
            return this.qsrch2_msg_textField;
        }
        set {
            this.qsrch2_msg_textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_sys_text {
        get {
            return this.qsrch2_sys_textField;
        }
        set {
            this.qsrch2_sys_textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QSRCH2")]
public partial class Qsrch2_areaQsrch2_input {
    
    private string qsrch2_source_sysField;
    
    private string qsrch2_in_nameField;
    
    private string qsrch2_in_idField;
    
    private string qsrch2_in_area_cdField;
    
    private string qsrch2_in_phoneField;
    
    private string qsrch2_in_ssnField;
    
    private string qsrch2_in_zipField;
    
    private string qsrch2_in_birthField;
    
    private string qsrch2_in_sysField;
    
    private string qsrch2_in_cmpField;
    
    private string qsrch2_in_name_typeField;
    
    private string qsrch2_in_lobField;
    
    private string qsrch2_in_stateField;
    
    private string qsrch2_eofField;
    
    private string qsrch2_more1Field;
    
    private string qsrch2_more2Field;
    
    private string qsrch2_more3Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_source_sys {
        get {
            return this.qsrch2_source_sysField;
        }
        set {
            this.qsrch2_source_sysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_name {
        get {
            return this.qsrch2_in_nameField;
        }
        set {
            this.qsrch2_in_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_id {
        get {
            return this.qsrch2_in_idField;
        }
        set {
            this.qsrch2_in_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_area_cd {
        get {
            return this.qsrch2_in_area_cdField;
        }
        set {
            this.qsrch2_in_area_cdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_phone {
        get {
            return this.qsrch2_in_phoneField;
        }
        set {
            this.qsrch2_in_phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_ssn {
        get {
            return this.qsrch2_in_ssnField;
        }
        set {
            this.qsrch2_in_ssnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_zip {
        get {
            return this.qsrch2_in_zipField;
        }
        set {
            this.qsrch2_in_zipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_birth {
        get {
            return this.qsrch2_in_birthField;
        }
        set {
            this.qsrch2_in_birthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_sys {
        get {
            return this.qsrch2_in_sysField;
        }
        set {
            this.qsrch2_in_sysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_cmp {
        get {
            return this.qsrch2_in_cmpField;
        }
        set {
            this.qsrch2_in_cmpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_name_type {
        get {
            return this.qsrch2_in_name_typeField;
        }
        set {
            this.qsrch2_in_name_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_lob {
        get {
            return this.qsrch2_in_lobField;
        }
        set {
            this.qsrch2_in_lobField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_in_state {
        get {
            return this.qsrch2_in_stateField;
        }
        set {
            this.qsrch2_in_stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_eof {
        get {
            return this.qsrch2_eofField;
        }
        set {
            this.qsrch2_eofField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_more1 {
        get {
            return this.qsrch2_more1Field;
        }
        set {
            this.qsrch2_more1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_more2 {
        get {
            return this.qsrch2_more2Field;
        }
        set {
            this.qsrch2_more2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qsrch2_more3 {
        get {
            return this.qsrch2_more3Field;
        }
        set {
            this.qsrch2_more3Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QSRCH2")]
public partial class Qsrch2_area {
    
    private Qsrch2_areaQsrch2_input qsrch2_inputField;
    
    private Qsrch2_areaQsrch2_msgs qsrch2_msgsField;
    
    private Qsrch2_areaQsrch2_output qsrch2_outputField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Qsrch2_areaQsrch2_input Qsrch2_input {
        get {
            return this.qsrch2_inputField;
        }
        set {
            this.qsrch2_inputField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Qsrch2_areaQsrch2_msgs Qsrch2_msgs {
        get {
            return this.qsrch2_msgsField;
        }
        set {
            this.qsrch2_msgsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Qsrch2_areaQsrch2_output Qsrch2_output {
        get {
            return this.qsrch2_outputField;
        }
        set {
            this.qsrch2_outputField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void CallQSRCH2CompletedEventHandler(object sender, CallQSRCH2CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CallQSRCH2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CallQSRCH2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Qsrch2_area Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Qsrch2_area)(this.results[0]));
        }
    }
}
