//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="CS01GENSoap", Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/CS01GEN")]
public partial class CS01GEN : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CallCS01GENOperationCompleted;
    
    /// <remarks/>
    public CS01GEN(string URL) {
        this.Url = URL;
    }
    
    /// <remarks/>
    public event CallCS01GENCompletedEventHandler CallCS01GENCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HTTP://SHADOW.CONSECO.COM/QSEARCH/CS01GEN/CS01GEN", RequestElementName="CS01GEN", RequestNamespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/CS01GEN", ResponseElementName="CS01GENResponse", ResponseNamespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/CS01GEN", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("CS01GENResult")]
    public Cs01gen_area CallCS01GEN(Cs01gen_input CS01GENInput) {
        object[] results = this.Invoke("CallCS01GEN", new object[] {
                    CS01GENInput});
        return ((Cs01gen_area)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCallCS01GEN(Cs01gen_input CS01GENInput, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CallCS01GEN", new object[] {
                    CS01GENInput}, callback, asyncState);
    }
    
    /// <remarks/>
    public Cs01gen_area EndCallCS01GEN(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Cs01gen_area)(results[0]));
    }
    
    /// <remarks/>
    public void CallCS01GENAsync(Cs01gen_input CS01GENInput) {
        this.CallCS01GENAsync(CS01GENInput, null);
    }
    
    /// <remarks/>
    public void CallCS01GENAsync(Cs01gen_input CS01GENInput, object userState) {
        if ((this.CallCS01GENOperationCompleted == null)) {
            this.CallCS01GENOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallCS01GENOperationCompleted);
        }
        this.InvokeAsync("CallCS01GEN", new object[] {
                    CS01GENInput}, this.CallCS01GENOperationCompleted, userState);
    }
    
    private void OnCallCS01GENOperationCompleted(object arg) {
        if ((this.CallCS01GENCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CallCS01GENCompleted(this, new CallCS01GENCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/CS01GEN")]
public partial class Cs01gen_input {
    
    private string cs01gen_typeField;
    
    private string cs01gen_systemField;
    
    private string cs01gen_companyField;
    
    private string cs01gen_idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_type {
        get {
            return this.cs01gen_typeField;
        }
        set {
            this.cs01gen_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_system {
        get {
            return this.cs01gen_systemField;
        }
        set {
            this.cs01gen_systemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_company {
        get {
            return this.cs01gen_companyField;
        }
        set {
            this.cs01gen_companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_id {
        get {
            return this.cs01gen_idField;
        }
        set {
            this.cs01gen_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/CS01GEN")]
public partial class Cs01gen_areaCs01gen_outputCs01gen_prsn_tbl {
    
    private string cs01gen_prsn_ptrField;
    
    private string cs01gen_prsn_nameField;
    
    private string cs01gen_prsn_sexField;
    
    private string cs01gen_prsn_dobField;
    
    private string cs01gen_prsn_rel1Field;
    
    private string cs01gen_prsn_rel2Field;
    
    private string cs01gen_prsn_rel3Field;
    
    private string cs01gen_prsn_rel4Field;
    
    private string cs01gen_prsn_medcField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_prsn_ptr {
        get {
            return this.cs01gen_prsn_ptrField;
        }
        set {
            this.cs01gen_prsn_ptrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_prsn_name {
        get {
            return this.cs01gen_prsn_nameField;
        }
        set {
            this.cs01gen_prsn_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_prsn_sex {
        get {
            return this.cs01gen_prsn_sexField;
        }
        set {
            this.cs01gen_prsn_sexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_prsn_dob {
        get {
            return this.cs01gen_prsn_dobField;
        }
        set {
            this.cs01gen_prsn_dobField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_prsn_rel1 {
        get {
            return this.cs01gen_prsn_rel1Field;
        }
        set {
            this.cs01gen_prsn_rel1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_prsn_rel2 {
        get {
            return this.cs01gen_prsn_rel2Field;
        }
        set {
            this.cs01gen_prsn_rel2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_prsn_rel3 {
        get {
            return this.cs01gen_prsn_rel3Field;
        }
        set {
            this.cs01gen_prsn_rel3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_prsn_rel4 {
        get {
            return this.cs01gen_prsn_rel4Field;
        }
        set {
            this.cs01gen_prsn_rel4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_prsn_medc {
        get {
            return this.cs01gen_prsn_medcField;
        }
        set {
            this.cs01gen_prsn_medcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/CS01GEN")]
public partial class Cs01gen_areaCs01gen_outputCs01gen_db_array {
    
    private string cs01gen_db_ptrField;
    
    private string cs01gen_db_textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_db_ptr {
        get {
            return this.cs01gen_db_ptrField;
        }
        set {
            this.cs01gen_db_ptrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_db_text {
        get {
            return this.cs01gen_db_textField;
        }
        set {
            this.cs01gen_db_textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/CS01GEN")]
public partial class Cs01gen_areaCs01gen_outputCs01gen_covg_array {
    
    private string cs01gen_covg_indField;
    
    private string cs01gen_covg_planField;
    
    private string cs01gen_covg_effField;
    
    private string cs01gen_covg_descField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_ind {
        get {
            return this.cs01gen_covg_indField;
        }
        set {
            this.cs01gen_covg_indField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_plan {
        get {
            return this.cs01gen_covg_planField;
        }
        set {
            this.cs01gen_covg_planField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_eff {
        get {
            return this.cs01gen_covg_effField;
        }
        set {
            this.cs01gen_covg_effField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_desc {
        get {
            return this.cs01gen_covg_descField;
        }
        set {
            this.cs01gen_covg_descField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/CS01GEN")]
public partial class Cs01gen_areaCs01gen_outputCs01gen_agt_tblCs01gen_agt_array {
    
    private string cs01gen_agt_lvlField;
    
    private string cs01gen_agt_idField;
    
    private string cs01gen_agt_nameField;
    
    private string cs01gen_agt_typeField;
    
    private string cs01gen_agt_res_indField;
    
    private string cs01gen_agt_stateField;
    
    private string cs01gen_agt_eff_dtField;
    
    private string cs01gen_agt_exp_dtField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_lvl {
        get {
            return this.cs01gen_agt_lvlField;
        }
        set {
            this.cs01gen_agt_lvlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_id {
        get {
            return this.cs01gen_agt_idField;
        }
        set {
            this.cs01gen_agt_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_name {
        get {
            return this.cs01gen_agt_nameField;
        }
        set {
            this.cs01gen_agt_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_type {
        get {
            return this.cs01gen_agt_typeField;
        }
        set {
            this.cs01gen_agt_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_res_ind {
        get {
            return this.cs01gen_agt_res_indField;
        }
        set {
            this.cs01gen_agt_res_indField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_state {
        get {
            return this.cs01gen_agt_stateField;
        }
        set {
            this.cs01gen_agt_stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_eff_dt {
        get {
            return this.cs01gen_agt_eff_dtField;
        }
        set {
            this.cs01gen_agt_eff_dtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_exp_dt {
        get {
            return this.cs01gen_agt_exp_dtField;
        }
        set {
            this.cs01gen_agt_exp_dtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/CS01GEN")]
public partial class Cs01gen_areaCs01gen_output {
    
    private string cs01gen_agt_noField;
    
    private string cs01gen_agt_nmField;
    
    private string cs01gen_agt_adrs1Field;
    
    private string cs01gen_agt_adrs2Field;
    
    private string cs01gen_agt_adrs3Field;
    
    private string cs01gen_agt_areaField;
    
    private string cs01gen_agt_phoneField;
    
    private string cs01gen_agt_fax_areaField;
    
    private string cs01gen_agt_fax_phoneField;
    
    private string cs01gen_agt_fin_ownField;
    
    private string cs01gen_agt_adrs_ownField;
    
    private string cs01gen_agt_net_prField;
    
    private string cs01gen_agt_statusField;
    
    private System.Nullable<short> cs01gen_agt_cntField;
    
    private bool cs01gen_agt_cntFieldSpecified;
    
    private Cs01gen_areaCs01gen_outputCs01gen_agt_tblCs01gen_agt_array[] cs01gen_agt_tblField;
    
    private string cs01gen_covg_eff_dateField;
    
    private string cs01gen_covg_paid_toField;
    
    private string cs01gen_covg_status_codeField;
    
    private string cs01gen_covg_status_descField;
    
    private string cs01gen_covg_suspend_cdField;
    
    private string cs01gen_covg_nameField;
    
    private string cs01gen_covg_premField;
    
    private string cs01gen_covg_modeField;
    
    private string cs01gen_covg_maturityField;
    
    private string cs01gen_covg_alertField;
    
    private string cs01gen_covg_convField;
    
    private string cs01gen_covg_ln7_msgField;
    
    private string cs01gen_covg_msgField;
    
    private System.Nullable<short> cs01gen_covg_cntField;
    
    private bool cs01gen_covg_cntFieldSpecified;
    
    private Cs01gen_areaCs01gen_outputCs01gen_covg_array[] cs01gen_covg_arrayField;
    
    private System.Nullable<short> cs01gen_db_cntField;
    
    private bool cs01gen_db_cntFieldSpecified;
    
    private Cs01gen_areaCs01gen_outputCs01gen_db_array[] cs01gen_db_arrayField;
    
    private string cs01gen_acct_last_acctField;
    
    private string cs01gen_acct_formField;
    
    private string cs01gen_acct_draftField;
    
    private string cs01gen_acct_ln21_msgField;
    
    private string cs01gen_acct_msgField;
    
    private string cs01gen_payor_nameField;
    
    private string cs01gen_payor_addr1Field;
    
    private string cs01gen_payor_addr2Field;
    
    private string cs01gen_payor_addr3Field;
    
    private string cs01gen_last_bill_dtField;
    
    private string cs01gen_bg_swField;
    
    private string[] cs01gen_bank_lineField;
    
    private string cs01gen_bank_typeField;
    
    private string cs01gen_bank_controlField;
    
    private string cs01gen_bank_acct_name1Field;
    
    private string cs01gen_bank_acct_name2Field;
    
    private string cs01gen_bank_routeField;
    
    private string cs01gen_bank_acct_nbrField;
    
    private string cs01gen_bank_last_transField;
    
    private string cs01gen_bank_amtField;
    
    private string[] cs01gen_grp_lineField;
    
    private string cs01gen_grp_typeField;
    
    private string cs01gen_grp_controlField;
    
    private string cs01gen_grp_acct_nbrField;
    
    private string cs01gen_gen_nameField;
    
    private string cs01gen_gen_addr1Field;
    
    private string cs01gen_gen_addr2Field;
    
    private string cs01gen_gen_addr3Field;
    
    private string cs01gen_gen_areaField;
    
    private string cs01gen_gen_phoneField;
    
    private string cs01gen_gen_issue_stField;
    
    private string cs01gen_gen_agentField;
    
    private string cs01gen_gen_agent_nameField;
    
    private string cs01gen_gen_issue_ageField;
    
    private string cs01gen_gen_msgField;
    
    private string cs01gen_ph_due_dateField;
    
    private string cs01gen_ph_amtField;
    
    private string cs01gen_ph_entry_dateField;
    
    private string cs01gen_val_nameField;
    
    private string cs01gen_val_addr1Field;
    
    private string cs01gen_val_addr2Field;
    
    private string cs01gen_val_addr3Field;
    
    private string cs01gen_val_as_ofField;
    
    private string cs01gen_val_accum_cvField;
    
    private string cs01gen_val_surr_chgField;
    
    private string cs01gen_val_surr_valField;
    
    private string cs01gen_val_surr_pctField;
    
    private string cs01gen_val_tot_prem_pdField;
    
    private string cs01gen_val_curr_int_rtField;
    
    private string cs01gen_val_max_part_wdField;
    
    private string cs01gen_val_max_pf_avlField;
    
    private string cs01gen_val_loan_payoffField;
    
    private string cs01gen_val_divd_accumField;
    
    private string cs01gen_val_coupon_accumField;
    
    private string cs01gen_val_guar_int_rtField;
    
    private string cs01gen_val_divd_optionField;
    
    private string cs01gen_val_max_loan_avlField;
    
    private string cs01gen_val_oyt_amtField;
    
    private string cs01gen_val_loan_int_rtField;
    
    private string cs01gen_val_tot_wdField;
    
    private string cs01gen_val_new_money_rtField;
    
    private string cs01gen_val_rem_pdf_balField;
    
    private string cs01gen_val_cv_of_puaField;
    
    private string cs01gen_val_face_amt_of_puaField;
    
    private string cs01gen_val_dboField;
    
    private string cs01gen_val_last_coi_amtField;
    
    private string cs01gen_val_last_coi_dtField;
    
    private string cs01gen_val_nfoField;
    
    private string cs01gen_val_tot_prem_tax_paidField;
    
    private string cs01gen_val_index_creditField;
    
    private string cs01gen_val_exp_chargeField;
    
    private string cs01gen_val_lobField;
    
    private string cs01gen_val_qual_cdField;
    
    private string cs01gen_val_system_iss_dtField;
    
    private string cs01gen_val_face_amtField;
    
    private string cs01gen_val_pay_up_dtField;
    
    private string cs01gen_val_flat_extraField;
    
    private string cs01gen_val_min_prem_amtField;
    
    private string cs01gen_val_map_dateField;
    
    private string cs01gen_val_matur_dateField;
    
    private string cs01gen_val_rating_tblField;
    
    private string cs01gen_val_smoke_classField;
    
    private string cs01gen_val_suspense_amtField;
    
    private System.Nullable<short> cs01gen_prsn_cntField;
    
    private bool cs01gen_prsn_cntFieldSpecified;
    
    private Cs01gen_areaCs01gen_outputCs01gen_prsn_tbl[] cs01gen_prsn_tblField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_no {
        get {
            return this.cs01gen_agt_noField;
        }
        set {
            this.cs01gen_agt_noField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_nm {
        get {
            return this.cs01gen_agt_nmField;
        }
        set {
            this.cs01gen_agt_nmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_adrs1 {
        get {
            return this.cs01gen_agt_adrs1Field;
        }
        set {
            this.cs01gen_agt_adrs1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_adrs2 {
        get {
            return this.cs01gen_agt_adrs2Field;
        }
        set {
            this.cs01gen_agt_adrs2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_adrs3 {
        get {
            return this.cs01gen_agt_adrs3Field;
        }
        set {
            this.cs01gen_agt_adrs3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_area {
        get {
            return this.cs01gen_agt_areaField;
        }
        set {
            this.cs01gen_agt_areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_phone {
        get {
            return this.cs01gen_agt_phoneField;
        }
        set {
            this.cs01gen_agt_phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_fax_area {
        get {
            return this.cs01gen_agt_fax_areaField;
        }
        set {
            this.cs01gen_agt_fax_areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_fax_phone {
        get {
            return this.cs01gen_agt_fax_phoneField;
        }
        set {
            this.cs01gen_agt_fax_phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_fin_own {
        get {
            return this.cs01gen_agt_fin_ownField;
        }
        set {
            this.cs01gen_agt_fin_ownField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_adrs_own {
        get {
            return this.cs01gen_agt_adrs_ownField;
        }
        set {
            this.cs01gen_agt_adrs_ownField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_net_pr {
        get {
            return this.cs01gen_agt_net_prField;
        }
        set {
            this.cs01gen_agt_net_prField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_agt_status {
        get {
            return this.cs01gen_agt_statusField;
        }
        set {
            this.cs01gen_agt_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> Cs01gen_agt_cnt {
        get {
            return this.cs01gen_agt_cntField;
        }
        set {
            this.cs01gen_agt_cntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Cs01gen_agt_cntSpecified {
        get {
            return this.cs01gen_agt_cntFieldSpecified;
        }
        set {
            this.cs01gen_agt_cntFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Cs01gen_agt_array")]
    public Cs01gen_areaCs01gen_outputCs01gen_agt_tblCs01gen_agt_array[] Cs01gen_agt_tbl {
        get {
            return this.cs01gen_agt_tblField;
        }
        set {
            this.cs01gen_agt_tblField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_eff_date {
        get {
            return this.cs01gen_covg_eff_dateField;
        }
        set {
            this.cs01gen_covg_eff_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_paid_to {
        get {
            return this.cs01gen_covg_paid_toField;
        }
        set {
            this.cs01gen_covg_paid_toField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_status_code {
        get {
            return this.cs01gen_covg_status_codeField;
        }
        set {
            this.cs01gen_covg_status_codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_status_desc {
        get {
            return this.cs01gen_covg_status_descField;
        }
        set {
            this.cs01gen_covg_status_descField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_suspend_cd {
        get {
            return this.cs01gen_covg_suspend_cdField;
        }
        set {
            this.cs01gen_covg_suspend_cdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_name {
        get {
            return this.cs01gen_covg_nameField;
        }
        set {
            this.cs01gen_covg_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_prem {
        get {
            return this.cs01gen_covg_premField;
        }
        set {
            this.cs01gen_covg_premField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_mode {
        get {
            return this.cs01gen_covg_modeField;
        }
        set {
            this.cs01gen_covg_modeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_maturity {
        get {
            return this.cs01gen_covg_maturityField;
        }
        set {
            this.cs01gen_covg_maturityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_alert {
        get {
            return this.cs01gen_covg_alertField;
        }
        set {
            this.cs01gen_covg_alertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_conv {
        get {
            return this.cs01gen_covg_convField;
        }
        set {
            this.cs01gen_covg_convField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_ln7_msg {
        get {
            return this.cs01gen_covg_ln7_msgField;
        }
        set {
            this.cs01gen_covg_ln7_msgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_covg_msg {
        get {
            return this.cs01gen_covg_msgField;
        }
        set {
            this.cs01gen_covg_msgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> Cs01gen_covg_cnt {
        get {
            return this.cs01gen_covg_cntField;
        }
        set {
            this.cs01gen_covg_cntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Cs01gen_covg_cntSpecified {
        get {
            return this.cs01gen_covg_cntFieldSpecified;
        }
        set {
            this.cs01gen_covg_cntFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cs01gen_covg_array", IsNullable=true)]
    public Cs01gen_areaCs01gen_outputCs01gen_covg_array[] Cs01gen_covg_array {
        get {
            return this.cs01gen_covg_arrayField;
        }
        set {
            this.cs01gen_covg_arrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> Cs01gen_db_cnt {
        get {
            return this.cs01gen_db_cntField;
        }
        set {
            this.cs01gen_db_cntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Cs01gen_db_cntSpecified {
        get {
            return this.cs01gen_db_cntFieldSpecified;
        }
        set {
            this.cs01gen_db_cntFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cs01gen_db_array", IsNullable=true)]
    public Cs01gen_areaCs01gen_outputCs01gen_db_array[] Cs01gen_db_array {
        get {
            return this.cs01gen_db_arrayField;
        }
        set {
            this.cs01gen_db_arrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_acct_last_acct {
        get {
            return this.cs01gen_acct_last_acctField;
        }
        set {
            this.cs01gen_acct_last_acctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_acct_form {
        get {
            return this.cs01gen_acct_formField;
        }
        set {
            this.cs01gen_acct_formField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_acct_draft {
        get {
            return this.cs01gen_acct_draftField;
        }
        set {
            this.cs01gen_acct_draftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_acct_ln21_msg {
        get {
            return this.cs01gen_acct_ln21_msgField;
        }
        set {
            this.cs01gen_acct_ln21_msgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_acct_msg {
        get {
            return this.cs01gen_acct_msgField;
        }
        set {
            this.cs01gen_acct_msgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_payor_name {
        get {
            return this.cs01gen_payor_nameField;
        }
        set {
            this.cs01gen_payor_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_payor_addr1 {
        get {
            return this.cs01gen_payor_addr1Field;
        }
        set {
            this.cs01gen_payor_addr1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_payor_addr2 {
        get {
            return this.cs01gen_payor_addr2Field;
        }
        set {
            this.cs01gen_payor_addr2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_payor_addr3 {
        get {
            return this.cs01gen_payor_addr3Field;
        }
        set {
            this.cs01gen_payor_addr3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_last_bill_dt {
        get {
            return this.cs01gen_last_bill_dtField;
        }
        set {
            this.cs01gen_last_bill_dtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_bg_sw {
        get {
            return this.cs01gen_bg_swField;
        }
        set {
            this.cs01gen_bg_swField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cs01gen_bank_line", IsNullable=true)]
    public string[] Cs01gen_bank_line {
        get {
            return this.cs01gen_bank_lineField;
        }
        set {
            this.cs01gen_bank_lineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_bank_type {
        get {
            return this.cs01gen_bank_typeField;
        }
        set {
            this.cs01gen_bank_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_bank_control {
        get {
            return this.cs01gen_bank_controlField;
        }
        set {
            this.cs01gen_bank_controlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_bank_acct_name1 {
        get {
            return this.cs01gen_bank_acct_name1Field;
        }
        set {
            this.cs01gen_bank_acct_name1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_bank_acct_name2 {
        get {
            return this.cs01gen_bank_acct_name2Field;
        }
        set {
            this.cs01gen_bank_acct_name2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_bank_route {
        get {
            return this.cs01gen_bank_routeField;
        }
        set {
            this.cs01gen_bank_routeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_bank_acct_nbr {
        get {
            return this.cs01gen_bank_acct_nbrField;
        }
        set {
            this.cs01gen_bank_acct_nbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_bank_last_trans {
        get {
            return this.cs01gen_bank_last_transField;
        }
        set {
            this.cs01gen_bank_last_transField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_bank_amt {
        get {
            return this.cs01gen_bank_amtField;
        }
        set {
            this.cs01gen_bank_amtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cs01gen_grp_line", IsNullable=true)]
    public string[] Cs01gen_grp_line {
        get {
            return this.cs01gen_grp_lineField;
        }
        set {
            this.cs01gen_grp_lineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_grp_type {
        get {
            return this.cs01gen_grp_typeField;
        }
        set {
            this.cs01gen_grp_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_grp_control {
        get {
            return this.cs01gen_grp_controlField;
        }
        set {
            this.cs01gen_grp_controlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_grp_acct_nbr {
        get {
            return this.cs01gen_grp_acct_nbrField;
        }
        set {
            this.cs01gen_grp_acct_nbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_gen_name {
        get {
            return this.cs01gen_gen_nameField;
        }
        set {
            this.cs01gen_gen_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_gen_addr1 {
        get {
            return this.cs01gen_gen_addr1Field;
        }
        set {
            this.cs01gen_gen_addr1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_gen_addr2 {
        get {
            return this.cs01gen_gen_addr2Field;
        }
        set {
            this.cs01gen_gen_addr2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_gen_addr3 {
        get {
            return this.cs01gen_gen_addr3Field;
        }
        set {
            this.cs01gen_gen_addr3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_gen_area {
        get {
            return this.cs01gen_gen_areaField;
        }
        set {
            this.cs01gen_gen_areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_gen_phone {
        get {
            return this.cs01gen_gen_phoneField;
        }
        set {
            this.cs01gen_gen_phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_gen_issue_st {
        get {
            return this.cs01gen_gen_issue_stField;
        }
        set {
            this.cs01gen_gen_issue_stField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_gen_agent {
        get {
            return this.cs01gen_gen_agentField;
        }
        set {
            this.cs01gen_gen_agentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_gen_agent_name {
        get {
            return this.cs01gen_gen_agent_nameField;
        }
        set {
            this.cs01gen_gen_agent_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_gen_issue_age {
        get {
            return this.cs01gen_gen_issue_ageField;
        }
        set {
            this.cs01gen_gen_issue_ageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_gen_msg {
        get {
            return this.cs01gen_gen_msgField;
        }
        set {
            this.cs01gen_gen_msgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_ph_due_date {
        get {
            return this.cs01gen_ph_due_dateField;
        }
        set {
            this.cs01gen_ph_due_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_ph_amt {
        get {
            return this.cs01gen_ph_amtField;
        }
        set {
            this.cs01gen_ph_amtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_ph_entry_date {
        get {
            return this.cs01gen_ph_entry_dateField;
        }
        set {
            this.cs01gen_ph_entry_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_name {
        get {
            return this.cs01gen_val_nameField;
        }
        set {
            this.cs01gen_val_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_addr1 {
        get {
            return this.cs01gen_val_addr1Field;
        }
        set {
            this.cs01gen_val_addr1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_addr2 {
        get {
            return this.cs01gen_val_addr2Field;
        }
        set {
            this.cs01gen_val_addr2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_addr3 {
        get {
            return this.cs01gen_val_addr3Field;
        }
        set {
            this.cs01gen_val_addr3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_as_of {
        get {
            return this.cs01gen_val_as_ofField;
        }
        set {
            this.cs01gen_val_as_ofField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_accum_cv {
        get {
            return this.cs01gen_val_accum_cvField;
        }
        set {
            this.cs01gen_val_accum_cvField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_surr_chg {
        get {
            return this.cs01gen_val_surr_chgField;
        }
        set {
            this.cs01gen_val_surr_chgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_surr_val {
        get {
            return this.cs01gen_val_surr_valField;
        }
        set {
            this.cs01gen_val_surr_valField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_surr_pct {
        get {
            return this.cs01gen_val_surr_pctField;
        }
        set {
            this.cs01gen_val_surr_pctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_tot_prem_pd {
        get {
            return this.cs01gen_val_tot_prem_pdField;
        }
        set {
            this.cs01gen_val_tot_prem_pdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_curr_int_rt {
        get {
            return this.cs01gen_val_curr_int_rtField;
        }
        set {
            this.cs01gen_val_curr_int_rtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_max_part_wd {
        get {
            return this.cs01gen_val_max_part_wdField;
        }
        set {
            this.cs01gen_val_max_part_wdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_max_pf_avl {
        get {
            return this.cs01gen_val_max_pf_avlField;
        }
        set {
            this.cs01gen_val_max_pf_avlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_loan_payoff {
        get {
            return this.cs01gen_val_loan_payoffField;
        }
        set {
            this.cs01gen_val_loan_payoffField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_divd_accum {
        get {
            return this.cs01gen_val_divd_accumField;
        }
        set {
            this.cs01gen_val_divd_accumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_coupon_accum {
        get {
            return this.cs01gen_val_coupon_accumField;
        }
        set {
            this.cs01gen_val_coupon_accumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_guar_int_rt {
        get {
            return this.cs01gen_val_guar_int_rtField;
        }
        set {
            this.cs01gen_val_guar_int_rtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_divd_option {
        get {
            return this.cs01gen_val_divd_optionField;
        }
        set {
            this.cs01gen_val_divd_optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_max_loan_avl {
        get {
            return this.cs01gen_val_max_loan_avlField;
        }
        set {
            this.cs01gen_val_max_loan_avlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_oyt_amt {
        get {
            return this.cs01gen_val_oyt_amtField;
        }
        set {
            this.cs01gen_val_oyt_amtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_loan_int_rt {
        get {
            return this.cs01gen_val_loan_int_rtField;
        }
        set {
            this.cs01gen_val_loan_int_rtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_tot_wd {
        get {
            return this.cs01gen_val_tot_wdField;
        }
        set {
            this.cs01gen_val_tot_wdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_new_money_rt {
        get {
            return this.cs01gen_val_new_money_rtField;
        }
        set {
            this.cs01gen_val_new_money_rtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_rem_pdf_bal {
        get {
            return this.cs01gen_val_rem_pdf_balField;
        }
        set {
            this.cs01gen_val_rem_pdf_balField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_cv_of_pua {
        get {
            return this.cs01gen_val_cv_of_puaField;
        }
        set {
            this.cs01gen_val_cv_of_puaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_face_amt_of_pua {
        get {
            return this.cs01gen_val_face_amt_of_puaField;
        }
        set {
            this.cs01gen_val_face_amt_of_puaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_dbo {
        get {
            return this.cs01gen_val_dboField;
        }
        set {
            this.cs01gen_val_dboField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_last_coi_amt {
        get {
            return this.cs01gen_val_last_coi_amtField;
        }
        set {
            this.cs01gen_val_last_coi_amtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_last_coi_dt {
        get {
            return this.cs01gen_val_last_coi_dtField;
        }
        set {
            this.cs01gen_val_last_coi_dtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_nfo {
        get {
            return this.cs01gen_val_nfoField;
        }
        set {
            this.cs01gen_val_nfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_tot_prem_tax_paid {
        get {
            return this.cs01gen_val_tot_prem_tax_paidField;
        }
        set {
            this.cs01gen_val_tot_prem_tax_paidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_index_credit {
        get {
            return this.cs01gen_val_index_creditField;
        }
        set {
            this.cs01gen_val_index_creditField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_exp_charge {
        get {
            return this.cs01gen_val_exp_chargeField;
        }
        set {
            this.cs01gen_val_exp_chargeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_lob {
        get {
            return this.cs01gen_val_lobField;
        }
        set {
            this.cs01gen_val_lobField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_qual_cd {
        get {
            return this.cs01gen_val_qual_cdField;
        }
        set {
            this.cs01gen_val_qual_cdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_system_iss_dt {
        get {
            return this.cs01gen_val_system_iss_dtField;
        }
        set {
            this.cs01gen_val_system_iss_dtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_face_amt {
        get {
            return this.cs01gen_val_face_amtField;
        }
        set {
            this.cs01gen_val_face_amtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_pay_up_dt {
        get {
            return this.cs01gen_val_pay_up_dtField;
        }
        set {
            this.cs01gen_val_pay_up_dtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_flat_extra {
        get {
            return this.cs01gen_val_flat_extraField;
        }
        set {
            this.cs01gen_val_flat_extraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_min_prem_amt {
        get {
            return this.cs01gen_val_min_prem_amtField;
        }
        set {
            this.cs01gen_val_min_prem_amtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_map_date {
        get {
            return this.cs01gen_val_map_dateField;
        }
        set {
            this.cs01gen_val_map_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_matur_date {
        get {
            return this.cs01gen_val_matur_dateField;
        }
        set {
            this.cs01gen_val_matur_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_rating_tbl {
        get {
            return this.cs01gen_val_rating_tblField;
        }
        set {
            this.cs01gen_val_rating_tblField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_smoke_class {
        get {
            return this.cs01gen_val_smoke_classField;
        }
        set {
            this.cs01gen_val_smoke_classField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_val_suspense_amt {
        get {
            return this.cs01gen_val_suspense_amtField;
        }
        set {
            this.cs01gen_val_suspense_amtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> Cs01gen_prsn_cnt {
        get {
            return this.cs01gen_prsn_cntField;
        }
        set {
            this.cs01gen_prsn_cntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool Cs01gen_prsn_cntSpecified {
        get {
            return this.cs01gen_prsn_cntFieldSpecified;
        }
        set {
            this.cs01gen_prsn_cntFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Cs01gen_prsn_tbl", IsNullable=true)]
    public Cs01gen_areaCs01gen_outputCs01gen_prsn_tbl[] Cs01gen_prsn_tbl {
        get {
            return this.cs01gen_prsn_tblField;
        }
        set {
            this.cs01gen_prsn_tblField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/CS01GEN")]
public partial class Cs01gen_areaCs01gen_msgs {
    
    private string cs01gen_msg_lvlField;
    
    private string cs01gen_msg_textField;
    
    private string cs01gen_sys_textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_msg_lvl {
        get {
            return this.cs01gen_msg_lvlField;
        }
        set {
            this.cs01gen_msg_lvlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_msg_text {
        get {
            return this.cs01gen_msg_textField;
        }
        set {
            this.cs01gen_msg_textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_sys_text {
        get {
            return this.cs01gen_sys_textField;
        }
        set {
            this.cs01gen_sys_textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/CS01GEN")]
public partial class Cs01gen_areaCs01gen_input {
    
    private string cs01gen_typeField;
    
    private string cs01gen_systemField;
    
    private string cs01gen_companyField;
    
    private string cs01gen_idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_type {
        get {
            return this.cs01gen_typeField;
        }
        set {
            this.cs01gen_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_system {
        get {
            return this.cs01gen_systemField;
        }
        set {
            this.cs01gen_systemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_company {
        get {
            return this.cs01gen_companyField;
        }
        set {
            this.cs01gen_companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Cs01gen_id {
        get {
            return this.cs01gen_idField;
        }
        set {
            this.cs01gen_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/CS01GEN")]
public partial class Cs01gen_area {
    
    private Cs01gen_areaCs01gen_input cs01gen_inputField;
    
    private Cs01gen_areaCs01gen_msgs cs01gen_msgsField;
    
    private Cs01gen_areaCs01gen_output cs01gen_outputField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Cs01gen_areaCs01gen_input Cs01gen_input {
        get {
            return this.cs01gen_inputField;
        }
        set {
            this.cs01gen_inputField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Cs01gen_areaCs01gen_msgs Cs01gen_msgs {
        get {
            return this.cs01gen_msgsField;
        }
        set {
            this.cs01gen_msgsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Cs01gen_areaCs01gen_output Cs01gen_output {
        get {
            return this.cs01gen_outputField;
        }
        set {
            this.cs01gen_outputField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void CallCS01GENCompletedEventHandler(object sender, CallCS01GENCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CallCS01GENCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CallCS01GENCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Cs01gen_area Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Cs01gen_area)(this.results[0]));
        }
    }
}
