//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="LPXGENSoap", Namespace="HTTP://SHADOW.CONSECO.COM/LPXSYSTEM/LPXGEN")]
public partial class LPXGEN : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback DOLPXGENOperationCompleted;
    
    /// <remarks/>
    public LPXGEN(string URL) {
        //this.Url = "http://MFWEBT.CONSECO.COM:6111/LPXSYSTEM/LPXGEN.zws";
        //this.Url = global::BPADataValidation.Properties.Settings.Default.BPADataValidation_LPXGEN;
       this.Url = URL;
    }
    
    /// <remarks/>
    public event DOLPXGENCompletedEventHandler DOLPXGENCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HTTP://SHADOW.CONSECO.COM/LPXSYSTEM/LPXGEN/DOLPXGEN", RequestNamespace="HTTP://SHADOW.CONSECO.COM/LPXSYSTEM/LPXGEN", ResponseNamespace="HTTP://SHADOW.CONSECO.COM/LPXSYSTEM/LPXGEN", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Lpgen_Area DOLPXGEN(Lpgen_Input DOLPXGENInput) {
        object[] results = this.Invoke("DOLPXGEN", new object[] {
                    DOLPXGENInput});
        return ((Lpgen_Area)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDOLPXGEN(Lpgen_Input DOLPXGENInput, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DOLPXGEN", new object[] {
                    DOLPXGENInput}, callback, asyncState);
    }
    
    /// <remarks/>
    public Lpgen_Area EndDOLPXGEN(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Lpgen_Area)(results[0]));
    }
    
    /// <remarks/>
    public void DOLPXGENAsync(Lpgen_Input DOLPXGENInput) {
        this.DOLPXGENAsync(DOLPXGENInput, null);
    }
    
    /// <remarks/>
    public void DOLPXGENAsync(Lpgen_Input DOLPXGENInput, object userState) {
        if ((this.DOLPXGENOperationCompleted == null)) {
            this.DOLPXGENOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDOLPXGENOperationCompleted);
        }
        this.InvokeAsync("DOLPXGEN", new object[] {
                    DOLPXGENInput}, this.DOLPXGENOperationCompleted, userState);
    }
    
    private void OnDOLPXGENOperationCompleted(object arg) {
        if ((this.DOLPXGENCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DOLPXGENCompleted(this, new DOLPXGENCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/LPXSYSTEM/LPXGEN")]
public partial class Lpgen_Input {
    
    private string lpgen_TypeField;
    
    private string lpgen_SystemField;
    
    private string lpgen_CompanyField;
    
    private string lpgen_IdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Type {
        get {
            return this.lpgen_TypeField;
        }
        set {
            this.lpgen_TypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_System {
        get {
            return this.lpgen_SystemField;
        }
        set {
            this.lpgen_SystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Company {
        get {
            return this.lpgen_CompanyField;
        }
        set {
            this.lpgen_CompanyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Id {
        get {
            return this.lpgen_IdField;
        }
        set {
            this.lpgen_IdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/LPXSYSTEM/LPXGEN")]
public partial class Lpgen_AreaLpgen_OutputLpprs_Record {
    
    private string lpprs_CmpField;
    
    private string lpprs_IdField;
    
    private string lpprs_SsnField;
    
    private string[] lpprs_Person_CdField;
    
    private string lpprs_IdentifierField;
    
    private string lpprs_LastField;
    
    private string lpprs_FirstField;
    
    private string lpprs_MiddleField;
    
    private string lpprs_Birth_DtField;
    
    private string lpprs_Addr_1Field;
    
    private string lpprs_Addr_2Field;
    
    private string lpprs_CityField;
    
    private string lpprs_StateField;
    
    private string lpprs_Zip_CodeField;
    
    private string lpprs_CountryField;
    
    private string lpprs_Home_PhoneField;
    
    private string lpprs_Bus_PhoneField;
    
    private string lpprs_Tax_IdField;
    
    private string lpprs_Medi_IdField;
    
    private string lpprs_Sex_CodeField;
    
    private string lpprs_EmailField;
    
    private string lpprs_Name_IndField;
    
    private string lpprs_FaxField;
    
    private string lpprs_Zip_BoxField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Cmp {
        get {
            return this.lpprs_CmpField;
        }
        set {
            this.lpprs_CmpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Id {
        get {
            return this.lpprs_IdField;
        }
        set {
            this.lpprs_IdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Ssn {
        get {
            return this.lpprs_SsnField;
        }
        set {
            this.lpprs_SsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Lpprs_Person_Cd", IsNullable=true)]
    public string[] Lpprs_Person_Cd {
        get {
            return this.lpprs_Person_CdField;
        }
        set {
            this.lpprs_Person_CdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Identifier {
        get {
            return this.lpprs_IdentifierField;
        }
        set {
            this.lpprs_IdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Last {
        get {
            return this.lpprs_LastField;
        }
        set {
            this.lpprs_LastField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_First {
        get {
            return this.lpprs_FirstField;
        }
        set {
            this.lpprs_FirstField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Middle {
        get {
            return this.lpprs_MiddleField;
        }
        set {
            this.lpprs_MiddleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Birth_Dt {
        get {
            return this.lpprs_Birth_DtField;
        }
        set {
            this.lpprs_Birth_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Addr_1 {
        get {
            return this.lpprs_Addr_1Field;
        }
        set {
            this.lpprs_Addr_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Addr_2 {
        get {
            return this.lpprs_Addr_2Field;
        }
        set {
            this.lpprs_Addr_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_City {
        get {
            return this.lpprs_CityField;
        }
        set {
            this.lpprs_CityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_State {
        get {
            return this.lpprs_StateField;
        }
        set {
            this.lpprs_StateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Zip_Code {
        get {
            return this.lpprs_Zip_CodeField;
        }
        set {
            this.lpprs_Zip_CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Country {
        get {
            return this.lpprs_CountryField;
        }
        set {
            this.lpprs_CountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Home_Phone {
        get {
            return this.lpprs_Home_PhoneField;
        }
        set {
            this.lpprs_Home_PhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Bus_Phone {
        get {
            return this.lpprs_Bus_PhoneField;
        }
        set {
            this.lpprs_Bus_PhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Tax_Id {
        get {
            return this.lpprs_Tax_IdField;
        }
        set {
            this.lpprs_Tax_IdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Medi_Id {
        get {
            return this.lpprs_Medi_IdField;
        }
        set {
            this.lpprs_Medi_IdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Sex_Code {
        get {
            return this.lpprs_Sex_CodeField;
        }
        set {
            this.lpprs_Sex_CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Email {
        get {
            return this.lpprs_EmailField;
        }
        set {
            this.lpprs_EmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Name_Ind {
        get {
            return this.lpprs_Name_IndField;
        }
        set {
            this.lpprs_Name_IndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Fax {
        get {
            return this.lpprs_FaxField;
        }
        set {
            this.lpprs_FaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpprs_Zip_Box {
        get {
            return this.lpprs_Zip_BoxField;
        }
        set {
            this.lpprs_Zip_BoxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/LPXSYSTEM/LPXGEN")]
public partial class Lpgen_AreaLpgen_OutputLpagt_Agent_Record {
    
    private string lpagt_Ad_CmpField;
    
    private string lpagt_Ad_IdField;
    
    private string lpagt_Ad_Agent_NbrField;
    
    private string lpagt_Ad_Agent_ProfField;
    
    private string lpagt_Ad_Agent_TypeField;
    
    private string lpagt_Ad_Comm_PctField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpagt_Ad_Cmp {
        get {
            return this.lpagt_Ad_CmpField;
        }
        set {
            this.lpagt_Ad_CmpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpagt_Ad_Id {
        get {
            return this.lpagt_Ad_IdField;
        }
        set {
            this.lpagt_Ad_IdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpagt_Ad_Agent_Nbr {
        get {
            return this.lpagt_Ad_Agent_NbrField;
        }
        set {
            this.lpagt_Ad_Agent_NbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpagt_Ad_Agent_Prof {
        get {
            return this.lpagt_Ad_Agent_ProfField;
        }
        set {
            this.lpagt_Ad_Agent_ProfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpagt_Ad_Agent_Type {
        get {
            return this.lpagt_Ad_Agent_TypeField;
        }
        set {
            this.lpagt_Ad_Agent_TypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpagt_Ad_Comm_Pct {
        get {
            return this.lpagt_Ad_Comm_PctField;
        }
        set {
            this.lpagt_Ad_Comm_PctField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/LPXSYSTEM/LPXGEN")]
public partial class Lpgen_AreaLpgen_OutputLpcov_Record {
    
    private string lpcov_CmpField;
    
    private string lpcov_IdField;
    
    private string lpcov_Benefit_SeqField;
    
    private string lpcov_Base_CovgField;
    
    private string lpcov_PlanField;
    
    private string lpcov_Status_CdField;
    
    private string lpcov_Status_RsnField;
    
    private string lpcov_Status_Chg_DtField;
    
    private string lpcov_Iss_DtField;
    
    private string lpcov_Mature_Expire_DtField;
    
    private string lpcov_Prod_CtgyField;
    
    private string lpcov_Nbr_Of_UnitsField;
    
    private string lpcov_Val_Per_UnitField;
    
    private string lpcov_Ann_PremField;
    
    private string lpcov_Ann_Prem_Per_UnitField;
    
    private string lpcov_Substd_IndField;
    
    private string lpcov_Par_IndField;
    
    private string lpcov_Iss_StField;
    
    private string lpcov_Eff_DtField;
    
    private string lpcov_Paid_To_DtField;
    
    private string lpcov_AmtField;
    
    private string lpcov_Underwriting_CdField;
    
    private string lpcov_Status_DtField;
    
    private string lpcov_Iss_AgeField;
    
    private string lpcov_Tbl_RatingField;
    
    private string lpcov_Flat_AmtField;
    
    private string lpcov_Pay_Up_DtField;
    
    private string lpcov_Table_CodeField;
    
    private string lpcov_Plan_DescField;
    
    private string lpcov_Pct_Cease_DtField;
    
    private string lpcov_Flat_Cease_DtField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Cmp {
        get {
            return this.lpcov_CmpField;
        }
        set {
            this.lpcov_CmpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Id {
        get {
            return this.lpcov_IdField;
        }
        set {
            this.lpcov_IdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Benefit_Seq {
        get {
            return this.lpcov_Benefit_SeqField;
        }
        set {
            this.lpcov_Benefit_SeqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Base_Covg {
        get {
            return this.lpcov_Base_CovgField;
        }
        set {
            this.lpcov_Base_CovgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Plan {
        get {
            return this.lpcov_PlanField;
        }
        set {
            this.lpcov_PlanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Status_Cd {
        get {
            return this.lpcov_Status_CdField;
        }
        set {
            this.lpcov_Status_CdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Status_Rsn {
        get {
            return this.lpcov_Status_RsnField;
        }
        set {
            this.lpcov_Status_RsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Status_Chg_Dt {
        get {
            return this.lpcov_Status_Chg_DtField;
        }
        set {
            this.lpcov_Status_Chg_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Iss_Dt {
        get {
            return this.lpcov_Iss_DtField;
        }
        set {
            this.lpcov_Iss_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Mature_Expire_Dt {
        get {
            return this.lpcov_Mature_Expire_DtField;
        }
        set {
            this.lpcov_Mature_Expire_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Prod_Ctgy {
        get {
            return this.lpcov_Prod_CtgyField;
        }
        set {
            this.lpcov_Prod_CtgyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Nbr_Of_Units {
        get {
            return this.lpcov_Nbr_Of_UnitsField;
        }
        set {
            this.lpcov_Nbr_Of_UnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Val_Per_Unit {
        get {
            return this.lpcov_Val_Per_UnitField;
        }
        set {
            this.lpcov_Val_Per_UnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Ann_Prem {
        get {
            return this.lpcov_Ann_PremField;
        }
        set {
            this.lpcov_Ann_PremField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Ann_Prem_Per_Unit {
        get {
            return this.lpcov_Ann_Prem_Per_UnitField;
        }
        set {
            this.lpcov_Ann_Prem_Per_UnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Substd_Ind {
        get {
            return this.lpcov_Substd_IndField;
        }
        set {
            this.lpcov_Substd_IndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Par_Ind {
        get {
            return this.lpcov_Par_IndField;
        }
        set {
            this.lpcov_Par_IndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Iss_St {
        get {
            return this.lpcov_Iss_StField;
        }
        set {
            this.lpcov_Iss_StField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Eff_Dt {
        get {
            return this.lpcov_Eff_DtField;
        }
        set {
            this.lpcov_Eff_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Paid_To_Dt {
        get {
            return this.lpcov_Paid_To_DtField;
        }
        set {
            this.lpcov_Paid_To_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Amt {
        get {
            return this.lpcov_AmtField;
        }
        set {
            this.lpcov_AmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Underwriting_Cd {
        get {
            return this.lpcov_Underwriting_CdField;
        }
        set {
            this.lpcov_Underwriting_CdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Status_Dt {
        get {
            return this.lpcov_Status_DtField;
        }
        set {
            this.lpcov_Status_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Iss_Age {
        get {
            return this.lpcov_Iss_AgeField;
        }
        set {
            this.lpcov_Iss_AgeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Tbl_Rating {
        get {
            return this.lpcov_Tbl_RatingField;
        }
        set {
            this.lpcov_Tbl_RatingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Flat_Amt {
        get {
            return this.lpcov_Flat_AmtField;
        }
        set {
            this.lpcov_Flat_AmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Pay_Up_Dt {
        get {
            return this.lpcov_Pay_Up_DtField;
        }
        set {
            this.lpcov_Pay_Up_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Table_Code {
        get {
            return this.lpcov_Table_CodeField;
        }
        set {
            this.lpcov_Table_CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Plan_Desc {
        get {
            return this.lpcov_Plan_DescField;
        }
        set {
            this.lpcov_Plan_DescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Pct_Cease_Dt {
        get {
            return this.lpcov_Pct_Cease_DtField;
        }
        set {
            this.lpcov_Pct_Cease_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpcov_Flat_Cease_Dt {
        get {
            return this.lpcov_Flat_Cease_DtField;
        }
        set {
            this.lpcov_Flat_Cease_DtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/LPXSYSTEM/LPXGEN")]
public partial class Lpgen_AreaLpgen_Output {
    
    private string lpgen_Pol_CmpField;
    
    private string lpgen_Pol_IdField;
    
    private string lpgen_Stat_CdField;
    
    private string lpgen_Stat_RsnField;
    
    private string lpgen_Stat_Chg_DtField;
    
    private string lpgen_Iss_DtField;
    
    private string lpgen_Orphan_PolField;
    
    private string lpgen_Bill_ModeField;
    
    private string lpgen_Form_CodeField;
    
    private string lpgen_Pdto_DtField;
    
    private string lpgen_LobField;
    
    private string lpgen_Susp_CdField;
    
    private string lpgen_Mode_PremField;
    
    private string lpgen_Loan_IndField;
    
    private string lpgen_Loan_AmtField;
    
    private string lpgen_Substd_IndField;
    
    private string lpgen_Prod_CtgyField;
    
    private string lpgen_Accum_ValField;
    
    private string lpgen_Surr_ChrgField;
    
    private string lpgen_Front_LoadField;
    
    private string lpgen_Oth_Exp_LoadField;
    
    private string lpgen_Coi_AmtField;
    
    private string lpgen_Spec_AmtField;
    
    private string lpgen_Vfund_BalField;
    
    private string lpgen_Tax_Qual_CdField;
    
    private string lpgen_Iss_StateField;
    
    private string lpgen_Cert_IndField;
    
    private string lpgen_Group_IdField;
    
    private string lpgen_Stat_DtField;
    
    private string lpgen_Pac_Bank_NameField;
    
    private string lpgen_Pac_Rout_NbrField;
    
    private string lpgen_Pac_Acct_NbrField;
    
    private string lpgen_Susp_RsnField;
    
    private string lpgen_Billed_To_DtField;
    
    private string lpgen_Last_Bill_DtField;
    
    private string lpgen_Mntly_PremField;
    
    private string lpgen_Qtrly_PremField;
    
    private string lpgen_Semi_PremField;
    
    private string lpgen_Annual_PremField;
    
    private string lpgen_Acv_Asof_DtField;
    
    private string lpgen_Ult_Tier_AmtField;
    
    private string lpgen_Curr_Tier_AmtField;
    
    private string lpgen_Surr_ValField;
    
    private string lpgen_Srv_Asof_DtField;
    
    private string lpgen_Remain_PrinField;
    
    private string lpgen_Remain_IntField;
    
    private string lpgen_Pdf_Remain_BalField;
    
    private string lpgen_Tot_WithdrawalsField;
    
    private string lpgen_Front_Load_PrcntField;
    
    private string lpgen_Mva_AdjustmentField;
    
    private string lpgen_Mva_Asof_DtField;
    
    private string lpgen_Last_Coi_DtField;
    
    private string lpgen_Net_Amt_At_RiskField;
    
    private string lpgen_Idx_CrdtField;
    
    private string lpgen_Lbal_Asof_DtField;
    
    private string lpgen_Curr_Loan_IntField;
    
    private string lpgen_Avail_Loan_AmtField;
    
    private string lpgen_Avl_Loan_Asof_DtField;
    
    private string lpgen_Tot_Prems_PdField;
    
    private string lpgen_New_Money_RateField;
    
    private string lpgen_New_Loan_RateField;
    
    private string lpgen_Guar_Int_RateField;
    
    private string lpgen_Tot_Int_EarnedField;
    
    private string lpgen_Divd_OptField;
    
    private string lpgen_Deposit_DivsField;
    
    private string lpgen_Deposit_CoupField;
    
    private string lpgen_Cv_PuaField;
    
    private string lpgen_DboField;
    
    private string lpgen_Cv_Oyt_AmtField;
    
    private string lpgen_Face_Amt_PuaField;
    
    private string lpgen_Susp_AmtField;
    
    private string lpgen_Min_PremField;
    
    private string lpgen_Doic_IndField;
    
    private string lpgen_Lit_IndField;
    
    private string lpgen_Smkr_RatingField;
    
    private string lpgen_Policy_FeeField;
    
    private string lpgen_Bank_Draft_DayField;
    
    private string lpgen_Last_Acct_DtField;
    
    private string lpgen_Bill_CodeField;
    
    private string lpgen_Map_DtField;
    
    private string lpgen_Surr_PctField;
    
    private string lpgen_Tot_Prem_Tax_PdField;
    
    private string lpgen_Max_Pntly_Fre_AvlField;
    
    private string lpgen_Min_Prem_PayField;
    
    private string lpgen_Curr_Int_RateField;
    
    private string lpgen_Max_Part_WithdrwlField;
    
    private string lpgen_Index_Pol_SwField;
    
    private string lpgen_Product_IdField;
    
    private string lpgen_Nfo_CodeField;
    
    private System.Nullable<short> lpcov_CntField;
    
    private Lpgen_AreaLpgen_OutputLpcov_Record[] lpcov_RecordField;
    
    private System.Nullable<short> lpagt_Ad_CntField;
    
    private Lpgen_AreaLpgen_OutputLpagt_Agent_Record[] lpagt_Agent_RecordField;
    
    private System.Nullable<short> lpprs_CntField;
    
    private Lpgen_AreaLpgen_OutputLpprs_Record[] lpprs_RecordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Pol_Cmp {
        get {
            return this.lpgen_Pol_CmpField;
        }
        set {
            this.lpgen_Pol_CmpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Pol_Id {
        get {
            return this.lpgen_Pol_IdField;
        }
        set {
            this.lpgen_Pol_IdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Stat_Cd {
        get {
            return this.lpgen_Stat_CdField;
        }
        set {
            this.lpgen_Stat_CdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Stat_Rsn {
        get {
            return this.lpgen_Stat_RsnField;
        }
        set {
            this.lpgen_Stat_RsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Stat_Chg_Dt {
        get {
            return this.lpgen_Stat_Chg_DtField;
        }
        set {
            this.lpgen_Stat_Chg_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Iss_Dt {
        get {
            return this.lpgen_Iss_DtField;
        }
        set {
            this.lpgen_Iss_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Orphan_Pol {
        get {
            return this.lpgen_Orphan_PolField;
        }
        set {
            this.lpgen_Orphan_PolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Bill_Mode {
        get {
            return this.lpgen_Bill_ModeField;
        }
        set {
            this.lpgen_Bill_ModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Form_Code {
        get {
            return this.lpgen_Form_CodeField;
        }
        set {
            this.lpgen_Form_CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Pdto_Dt {
        get {
            return this.lpgen_Pdto_DtField;
        }
        set {
            this.lpgen_Pdto_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Lob {
        get {
            return this.lpgen_LobField;
        }
        set {
            this.lpgen_LobField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Susp_Cd {
        get {
            return this.lpgen_Susp_CdField;
        }
        set {
            this.lpgen_Susp_CdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Mode_Prem {
        get {
            return this.lpgen_Mode_PremField;
        }
        set {
            this.lpgen_Mode_PremField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Loan_Ind {
        get {
            return this.lpgen_Loan_IndField;
        }
        set {
            this.lpgen_Loan_IndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Loan_Amt {
        get {
            return this.lpgen_Loan_AmtField;
        }
        set {
            this.lpgen_Loan_AmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Substd_Ind {
        get {
            return this.lpgen_Substd_IndField;
        }
        set {
            this.lpgen_Substd_IndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Prod_Ctgy {
        get {
            return this.lpgen_Prod_CtgyField;
        }
        set {
            this.lpgen_Prod_CtgyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Accum_Val {
        get {
            return this.lpgen_Accum_ValField;
        }
        set {
            this.lpgen_Accum_ValField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Surr_Chrg {
        get {
            return this.lpgen_Surr_ChrgField;
        }
        set {
            this.lpgen_Surr_ChrgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Front_Load {
        get {
            return this.lpgen_Front_LoadField;
        }
        set {
            this.lpgen_Front_LoadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Oth_Exp_Load {
        get {
            return this.lpgen_Oth_Exp_LoadField;
        }
        set {
            this.lpgen_Oth_Exp_LoadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Coi_Amt {
        get {
            return this.lpgen_Coi_AmtField;
        }
        set {
            this.lpgen_Coi_AmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Spec_Amt {
        get {
            return this.lpgen_Spec_AmtField;
        }
        set {
            this.lpgen_Spec_AmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Vfund_Bal {
        get {
            return this.lpgen_Vfund_BalField;
        }
        set {
            this.lpgen_Vfund_BalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Tax_Qual_Cd {
        get {
            return this.lpgen_Tax_Qual_CdField;
        }
        set {
            this.lpgen_Tax_Qual_CdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Iss_State {
        get {
            return this.lpgen_Iss_StateField;
        }
        set {
            this.lpgen_Iss_StateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Cert_Ind {
        get {
            return this.lpgen_Cert_IndField;
        }
        set {
            this.lpgen_Cert_IndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Group_Id {
        get {
            return this.lpgen_Group_IdField;
        }
        set {
            this.lpgen_Group_IdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Stat_Dt {
        get {
            return this.lpgen_Stat_DtField;
        }
        set {
            this.lpgen_Stat_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Pac_Bank_Name {
        get {
            return this.lpgen_Pac_Bank_NameField;
        }
        set {
            this.lpgen_Pac_Bank_NameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Pac_Rout_Nbr {
        get {
            return this.lpgen_Pac_Rout_NbrField;
        }
        set {
            this.lpgen_Pac_Rout_NbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Pac_Acct_Nbr {
        get {
            return this.lpgen_Pac_Acct_NbrField;
        }
        set {
            this.lpgen_Pac_Acct_NbrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Susp_Rsn {
        get {
            return this.lpgen_Susp_RsnField;
        }
        set {
            this.lpgen_Susp_RsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Billed_To_Dt {
        get {
            return this.lpgen_Billed_To_DtField;
        }
        set {
            this.lpgen_Billed_To_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Last_Bill_Dt {
        get {
            return this.lpgen_Last_Bill_DtField;
        }
        set {
            this.lpgen_Last_Bill_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Mntly_Prem {
        get {
            return this.lpgen_Mntly_PremField;
        }
        set {
            this.lpgen_Mntly_PremField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Qtrly_Prem {
        get {
            return this.lpgen_Qtrly_PremField;
        }
        set {
            this.lpgen_Qtrly_PremField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Semi_Prem {
        get {
            return this.lpgen_Semi_PremField;
        }
        set {
            this.lpgen_Semi_PremField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Annual_Prem {
        get {
            return this.lpgen_Annual_PremField;
        }
        set {
            this.lpgen_Annual_PremField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Acv_Asof_Dt {
        get {
            return this.lpgen_Acv_Asof_DtField;
        }
        set {
            this.lpgen_Acv_Asof_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Ult_Tier_Amt {
        get {
            return this.lpgen_Ult_Tier_AmtField;
        }
        set {
            this.lpgen_Ult_Tier_AmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Curr_Tier_Amt {
        get {
            return this.lpgen_Curr_Tier_AmtField;
        }
        set {
            this.lpgen_Curr_Tier_AmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Surr_Val {
        get {
            return this.lpgen_Surr_ValField;
        }
        set {
            this.lpgen_Surr_ValField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Srv_Asof_Dt {
        get {
            return this.lpgen_Srv_Asof_DtField;
        }
        set {
            this.lpgen_Srv_Asof_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Remain_Prin {
        get {
            return this.lpgen_Remain_PrinField;
        }
        set {
            this.lpgen_Remain_PrinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Remain_Int {
        get {
            return this.lpgen_Remain_IntField;
        }
        set {
            this.lpgen_Remain_IntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Pdf_Remain_Bal {
        get {
            return this.lpgen_Pdf_Remain_BalField;
        }
        set {
            this.lpgen_Pdf_Remain_BalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Tot_Withdrawals {
        get {
            return this.lpgen_Tot_WithdrawalsField;
        }
        set {
            this.lpgen_Tot_WithdrawalsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Front_Load_Prcnt {
        get {
            return this.lpgen_Front_Load_PrcntField;
        }
        set {
            this.lpgen_Front_Load_PrcntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Mva_Adjustment {
        get {
            return this.lpgen_Mva_AdjustmentField;
        }
        set {
            this.lpgen_Mva_AdjustmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Mva_Asof_Dt {
        get {
            return this.lpgen_Mva_Asof_DtField;
        }
        set {
            this.lpgen_Mva_Asof_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Last_Coi_Dt {
        get {
            return this.lpgen_Last_Coi_DtField;
        }
        set {
            this.lpgen_Last_Coi_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Net_Amt_At_Risk {
        get {
            return this.lpgen_Net_Amt_At_RiskField;
        }
        set {
            this.lpgen_Net_Amt_At_RiskField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Idx_Crdt {
        get {
            return this.lpgen_Idx_CrdtField;
        }
        set {
            this.lpgen_Idx_CrdtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Lbal_Asof_Dt {
        get {
            return this.lpgen_Lbal_Asof_DtField;
        }
        set {
            this.lpgen_Lbal_Asof_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Curr_Loan_Int {
        get {
            return this.lpgen_Curr_Loan_IntField;
        }
        set {
            this.lpgen_Curr_Loan_IntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Avail_Loan_Amt {
        get {
            return this.lpgen_Avail_Loan_AmtField;
        }
        set {
            this.lpgen_Avail_Loan_AmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Avl_Loan_Asof_Dt {
        get {
            return this.lpgen_Avl_Loan_Asof_DtField;
        }
        set {
            this.lpgen_Avl_Loan_Asof_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Tot_Prems_Pd {
        get {
            return this.lpgen_Tot_Prems_PdField;
        }
        set {
            this.lpgen_Tot_Prems_PdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_New_Money_Rate {
        get {
            return this.lpgen_New_Money_RateField;
        }
        set {
            this.lpgen_New_Money_RateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_New_Loan_Rate {
        get {
            return this.lpgen_New_Loan_RateField;
        }
        set {
            this.lpgen_New_Loan_RateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Guar_Int_Rate {
        get {
            return this.lpgen_Guar_Int_RateField;
        }
        set {
            this.lpgen_Guar_Int_RateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Tot_Int_Earned {
        get {
            return this.lpgen_Tot_Int_EarnedField;
        }
        set {
            this.lpgen_Tot_Int_EarnedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Divd_Opt {
        get {
            return this.lpgen_Divd_OptField;
        }
        set {
            this.lpgen_Divd_OptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Deposit_Divs {
        get {
            return this.lpgen_Deposit_DivsField;
        }
        set {
            this.lpgen_Deposit_DivsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Deposit_Coup {
        get {
            return this.lpgen_Deposit_CoupField;
        }
        set {
            this.lpgen_Deposit_CoupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Cv_Pua {
        get {
            return this.lpgen_Cv_PuaField;
        }
        set {
            this.lpgen_Cv_PuaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Dbo {
        get {
            return this.lpgen_DboField;
        }
        set {
            this.lpgen_DboField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Cv_Oyt_Amt {
        get {
            return this.lpgen_Cv_Oyt_AmtField;
        }
        set {
            this.lpgen_Cv_Oyt_AmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Face_Amt_Pua {
        get {
            return this.lpgen_Face_Amt_PuaField;
        }
        set {
            this.lpgen_Face_Amt_PuaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Susp_Amt {
        get {
            return this.lpgen_Susp_AmtField;
        }
        set {
            this.lpgen_Susp_AmtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Min_Prem {
        get {
            return this.lpgen_Min_PremField;
        }
        set {
            this.lpgen_Min_PremField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Doic_Ind {
        get {
            return this.lpgen_Doic_IndField;
        }
        set {
            this.lpgen_Doic_IndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Lit_Ind {
        get {
            return this.lpgen_Lit_IndField;
        }
        set {
            this.lpgen_Lit_IndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Smkr_Rating {
        get {
            return this.lpgen_Smkr_RatingField;
        }
        set {
            this.lpgen_Smkr_RatingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Policy_Fee {
        get {
            return this.lpgen_Policy_FeeField;
        }
        set {
            this.lpgen_Policy_FeeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Bank_Draft_Day {
        get {
            return this.lpgen_Bank_Draft_DayField;
        }
        set {
            this.lpgen_Bank_Draft_DayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Last_Acct_Dt {
        get {
            return this.lpgen_Last_Acct_DtField;
        }
        set {
            this.lpgen_Last_Acct_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Bill_Code {
        get {
            return this.lpgen_Bill_CodeField;
        }
        set {
            this.lpgen_Bill_CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Map_Dt {
        get {
            return this.lpgen_Map_DtField;
        }
        set {
            this.lpgen_Map_DtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Surr_Pct {
        get {
            return this.lpgen_Surr_PctField;
        }
        set {
            this.lpgen_Surr_PctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Tot_Prem_Tax_Pd {
        get {
            return this.lpgen_Tot_Prem_Tax_PdField;
        }
        set {
            this.lpgen_Tot_Prem_Tax_PdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Max_Pntly_Fre_Avl {
        get {
            return this.lpgen_Max_Pntly_Fre_AvlField;
        }
        set {
            this.lpgen_Max_Pntly_Fre_AvlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Min_Prem_Pay {
        get {
            return this.lpgen_Min_Prem_PayField;
        }
        set {
            this.lpgen_Min_Prem_PayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Curr_Int_Rate {
        get {
            return this.lpgen_Curr_Int_RateField;
        }
        set {
            this.lpgen_Curr_Int_RateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Max_Part_Withdrwl {
        get {
            return this.lpgen_Max_Part_WithdrwlField;
        }
        set {
            this.lpgen_Max_Part_WithdrwlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Index_Pol_Sw {
        get {
            return this.lpgen_Index_Pol_SwField;
        }
        set {
            this.lpgen_Index_Pol_SwField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Product_Id {
        get {
            return this.lpgen_Product_IdField;
        }
        set {
            this.lpgen_Product_IdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Nfo_Code {
        get {
            return this.lpgen_Nfo_CodeField;
        }
        set {
            this.lpgen_Nfo_CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> Lpcov_Cnt {
        get {
            return this.lpcov_CntField;
        }
        set {
            this.lpcov_CntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Lpcov_Record", IsNullable=true)]
    public Lpgen_AreaLpgen_OutputLpcov_Record[] Lpcov_Record {
        get {
            return this.lpcov_RecordField;
        }
        set {
            this.lpcov_RecordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> Lpagt_Ad_Cnt {
        get {
            return this.lpagt_Ad_CntField;
        }
        set {
            this.lpagt_Ad_CntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Lpagt_Agent_Record", IsNullable=true)]
    public Lpgen_AreaLpgen_OutputLpagt_Agent_Record[] Lpagt_Agent_Record {
        get {
            return this.lpagt_Agent_RecordField;
        }
        set {
            this.lpagt_Agent_RecordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> Lpprs_Cnt {
        get {
            return this.lpprs_CntField;
        }
        set {
            this.lpprs_CntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Lpprs_Record", IsNullable=true)]
    public Lpgen_AreaLpgen_OutputLpprs_Record[] Lpprs_Record {
        get {
            return this.lpprs_RecordField;
        }
        set {
            this.lpprs_RecordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/LPXSYSTEM/LPXGEN")]
public partial class Lpgen_AreaLpgen_Msgs {
    
    private string lpgen_Msg_LvlField;
    
    private string lpgen_Msg_TextField;
    
    private string lpgen_Sys_TextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Msg_Lvl {
        get {
            return this.lpgen_Msg_LvlField;
        }
        set {
            this.lpgen_Msg_LvlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Msg_Text {
        get {
            return this.lpgen_Msg_TextField;
        }
        set {
            this.lpgen_Msg_TextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Sys_Text {
        get {
            return this.lpgen_Sys_TextField;
        }
        set {
            this.lpgen_Sys_TextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/LPXSYSTEM/LPXGEN")]
public partial class Lpgen_AreaLpgen_Input {
    
    private string lpgen_TypeField;
    
    private string lpgen_SystemField;
    
    private string lpgen_CompanyField;
    
    private string lpgen_IdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Type {
        get {
            return this.lpgen_TypeField;
        }
        set {
            this.lpgen_TypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_System {
        get {
            return this.lpgen_SystemField;
        }
        set {
            this.lpgen_SystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Company {
        get {
            return this.lpgen_CompanyField;
        }
        set {
            this.lpgen_CompanyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Lpgen_Id {
        get {
            return this.lpgen_IdField;
        }
        set {
            this.lpgen_IdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/LPXSYSTEM/LPXGEN")]
public partial class Lpgen_Area {
    
    private Lpgen_AreaLpgen_Input lpgen_InputField;
    
    private Lpgen_AreaLpgen_Msgs lpgen_MsgsField;
    
    private Lpgen_AreaLpgen_Output lpgen_OutputField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Lpgen_AreaLpgen_Input Lpgen_Input {
        get {
            return this.lpgen_InputField;
        }
        set {
            this.lpgen_InputField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Lpgen_AreaLpgen_Msgs Lpgen_Msgs {
        get {
            return this.lpgen_MsgsField;
        }
        set {
            this.lpgen_MsgsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Lpgen_AreaLpgen_Output Lpgen_Output {
        get {
            return this.lpgen_OutputField;
        }
        set {
            this.lpgen_OutputField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void DOLPXGENCompletedEventHandler(object sender, DOLPXGENCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DOLPXGENCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DOLPXGENCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Lpgen_Area Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Lpgen_Area)(this.results[0]));
        }
    }
}
