//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="QDETLSoap", Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QDETL")]
public partial class QDETL : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback DODETLOperationCompleted;
    
    /// <remarks/>
    public QDETL(string URL) {
        //this.Url = "http://MFWEBT.CONSECO.COM:6111/QSEARCH/QDETL.zws";
       this.Url = URL;
    }
    
    /// <remarks/>
    public event DODETLCompletedEventHandler DODETLCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("HTTP://SHADOW.CONSECO.COM/QSEARCH/QDETL/DODETL", RequestNamespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QDETL", ResponseNamespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QDETL", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Qdetl_Area DODETL(Qdetl_Input DODETLInput) {
        object[] results = this.Invoke("DODETL", new object[] {
                    DODETLInput});
        return ((Qdetl_Area)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDODETL(Qdetl_Input DODETLInput, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DODETL", new object[] {
                    DODETLInput}, callback, asyncState);
    }
    
    /// <remarks/>
    public Qdetl_Area EndDODETL(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Qdetl_Area)(results[0]));
    }
    
    /// <remarks/>
    public void DODETLAsync(Qdetl_Input DODETLInput) {
        this.DODETLAsync(DODETLInput, null);
    }
    
    /// <remarks/>
    public void DODETLAsync(Qdetl_Input DODETLInput, object userState) {
        if ((this.DODETLOperationCompleted == null)) {
            this.DODETLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDODETLOperationCompleted);
        }
        this.InvokeAsync("DODETL", new object[] {
                    DODETLInput}, this.DODETLOperationCompleted, userState);
    }
    
    private void OnDODETLOperationCompleted(object arg) {
        if ((this.DODETLCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DODETLCompleted(this, new DODETLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QDETL")]
public partial class Qdetl_Input {
    
    private string qdetl_TypeField;
    
    private string qdetl_SystemField;
    
    private string qdetl_CompanyField;
    
    private string qdetl_IdField;
    
    private string qdetl_UseridField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Type {
        get {
            return this.qdetl_TypeField;
        }
        set {
            this.qdetl_TypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_System {
        get {
            return this.qdetl_SystemField;
        }
        set {
            this.qdetl_SystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Company {
        get {
            return this.qdetl_CompanyField;
        }
        set {
            this.qdetl_CompanyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Id {
        get {
            return this.qdetl_IdField;
        }
        set {
            this.qdetl_IdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Userid {
        get {
            return this.qdetl_UseridField;
        }
        set {
            this.qdetl_UseridField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QDETL")]
public partial class Qdetl_AreaQdetl_OutputQdetl_Pop_ArrayQdetl_Pop_Lines {
    
    private string qdetl_Pop_CdField;
    
    private string qdetl_Pop_MsgField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Pop_Cd {
        get {
            return this.qdetl_Pop_CdField;
        }
        set {
            this.qdetl_Pop_CdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Pop_Msg {
        get {
            return this.qdetl_Pop_MsgField;
        }
        set {
            this.qdetl_Pop_MsgField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QDETL")]
public partial class Qdetl_AreaQdetl_OutputQdetl_Misc {
    
    private string qdetl_LocationField;
    
    private string qdetl_Sys_DescField;
    
    private string qdetl_Cmp_DescField;
    
    private string qdetl_Togo_TypeField;
    
    private string qdetl_Togo_SysField;
    
    private string qdetl_Togo_CmpField;
    
    private string qdetl_Togo_IdField;
    
    private string qdetl_Bptr_TypeField;
    
    private string qdetl_Bptr_SysField;
    
    private string qdetl_Bptr_CmpField;
    
    private string qdetl_Bptr_IdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Location {
        get {
            return this.qdetl_LocationField;
        }
        set {
            this.qdetl_LocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Sys_Desc {
        get {
            return this.qdetl_Sys_DescField;
        }
        set {
            this.qdetl_Sys_DescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Cmp_Desc {
        get {
            return this.qdetl_Cmp_DescField;
        }
        set {
            this.qdetl_Cmp_DescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Togo_Type {
        get {
            return this.qdetl_Togo_TypeField;
        }
        set {
            this.qdetl_Togo_TypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Togo_Sys {
        get {
            return this.qdetl_Togo_SysField;
        }
        set {
            this.qdetl_Togo_SysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Togo_Cmp {
        get {
            return this.qdetl_Togo_CmpField;
        }
        set {
            this.qdetl_Togo_CmpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Togo_Id {
        get {
            return this.qdetl_Togo_IdField;
        }
        set {
            this.qdetl_Togo_IdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Bptr_Type {
        get {
            return this.qdetl_Bptr_TypeField;
        }
        set {
            this.qdetl_Bptr_TypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Bptr_Sys {
        get {
            return this.qdetl_Bptr_SysField;
        }
        set {
            this.qdetl_Bptr_SysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Bptr_Cmp {
        get {
            return this.qdetl_Bptr_CmpField;
        }
        set {
            this.qdetl_Bptr_CmpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Bptr_Id {
        get {
            return this.qdetl_Bptr_IdField;
        }
        set {
            this.qdetl_Bptr_IdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QDETL")]
public partial class Qdetl_AreaQdetl_OutputQdetl_Array {
    
    private string qdetl_SsnField;
    
    private string qdetl_NameField;
    
    private string qdetl_Addr_1Field;
    
    private string qdetl_Addr_2Field;
    
    private string qdetl_CityField;
    
    private string qdetl_StField;
    
    private string qdetl_ZipField;
    
    private string qdetl_CountryField;
    
    private string qdetl_Area_CodeField;
    
    private string qdetl_PhoneField;
    
    private string qdetl_BirthField;
    
    private string qdetl_SexField;
    
    private string[] qdetl_RelField;
    
    private string qdetl_ProductField;
    
    private string qdetl_LobField;
    
    private string qdetl_StatusField;
    
    private string qdetl_Last_ActivityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Ssn {
        get {
            return this.qdetl_SsnField;
        }
        set {
            this.qdetl_SsnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Name {
        get {
            return this.qdetl_NameField;
        }
        set {
            this.qdetl_NameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Addr_1 {
        get {
            return this.qdetl_Addr_1Field;
        }
        set {
            this.qdetl_Addr_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Addr_2 {
        get {
            return this.qdetl_Addr_2Field;
        }
        set {
            this.qdetl_Addr_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_City {
        get {
            return this.qdetl_CityField;
        }
        set {
            this.qdetl_CityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_St {
        get {
            return this.qdetl_StField;
        }
        set {
            this.qdetl_StField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Zip {
        get {
            return this.qdetl_ZipField;
        }
        set {
            this.qdetl_ZipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Country {
        get {
            return this.qdetl_CountryField;
        }
        set {
            this.qdetl_CountryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Area_Code {
        get {
            return this.qdetl_Area_CodeField;
        }
        set {
            this.qdetl_Area_CodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Phone {
        get {
            return this.qdetl_PhoneField;
        }
        set {
            this.qdetl_PhoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Birth {
        get {
            return this.qdetl_BirthField;
        }
        set {
            this.qdetl_BirthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Sex {
        get {
            return this.qdetl_SexField;
        }
        set {
            this.qdetl_SexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Qdetl_Rel", IsNullable=true)]
    public string[] Qdetl_Rel {
        get {
            return this.qdetl_RelField;
        }
        set {
            this.qdetl_RelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Product {
        get {
            return this.qdetl_ProductField;
        }
        set {
            this.qdetl_ProductField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Lob {
        get {
            return this.qdetl_LobField;
        }
        set {
            this.qdetl_LobField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Status {
        get {
            return this.qdetl_StatusField;
        }
        set {
            this.qdetl_StatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Last_Activity {
        get {
            return this.qdetl_Last_ActivityField;
        }
        set {
            this.qdetl_Last_ActivityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QDETL")]
public partial class Qdetl_AreaQdetl_Output {
    
    private System.Nullable<short> qdetl_Prsn_CntField;
    
    private Qdetl_AreaQdetl_OutputQdetl_Array[] qdetl_ArrayField;
    
    private Qdetl_AreaQdetl_OutputQdetl_Misc qdetl_MiscField;
    
    private System.Nullable<short> qdetl_Pop_Approved_CntField;
    
    private System.Nullable<short> qdetl_Pop_Severe_CntField;
    
    private System.Nullable<short> qdetl_Pop_CntField;
    
    private Qdetl_AreaQdetl_OutputQdetl_Pop_ArrayQdetl_Pop_Lines[] qdetl_Pop_ArrayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> Qdetl_Prsn_Cnt {
        get {
            return this.qdetl_Prsn_CntField;
        }
        set {
            this.qdetl_Prsn_CntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Qdetl_Array", IsNullable=true)]
    public Qdetl_AreaQdetl_OutputQdetl_Array[] Qdetl_Array {
        get {
            return this.qdetl_ArrayField;
        }
        set {
            this.qdetl_ArrayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Qdetl_AreaQdetl_OutputQdetl_Misc Qdetl_Misc {
        get {
            return this.qdetl_MiscField;
        }
        set {
            this.qdetl_MiscField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> Qdetl_Pop_Approved_Cnt {
        get {
            return this.qdetl_Pop_Approved_CntField;
        }
        set {
            this.qdetl_Pop_Approved_CntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> Qdetl_Pop_Severe_Cnt {
        get {
            return this.qdetl_Pop_Severe_CntField;
        }
        set {
            this.qdetl_Pop_Severe_CntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> Qdetl_Pop_Cnt {
        get {
            return this.qdetl_Pop_CntField;
        }
        set {
            this.qdetl_Pop_CntField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Qdetl_Pop_Lines")]
    public Qdetl_AreaQdetl_OutputQdetl_Pop_ArrayQdetl_Pop_Lines[] Qdetl_Pop_Array {
        get {
            return this.qdetl_Pop_ArrayField;
        }
        set {
            this.qdetl_Pop_ArrayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QDETL")]
public partial class Qdetl_AreaQdetl_Msgs {
    
    private string qdetl_Msg_LvlField;
    
    private string qdetl_Msg_TextField;
    
    private string qdetl_Sys_TextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Msg_Lvl {
        get {
            return this.qdetl_Msg_LvlField;
        }
        set {
            this.qdetl_Msg_LvlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Msg_Text {
        get {
            return this.qdetl_Msg_TextField;
        }
        set {
            this.qdetl_Msg_TextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Sys_Text {
        get {
            return this.qdetl_Sys_TextField;
        }
        set {
            this.qdetl_Sys_TextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QDETL")]
public partial class Qdetl_AreaQdetl_Input {
    
    private string qdetl_TypeField;
    
    private string qdetl_SystemField;
    
    private string qdetl_CompanyField;
    
    private string qdetl_IdField;
    
    private string qdetl_UseridField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Type {
        get {
            return this.qdetl_TypeField;
        }
        set {
            this.qdetl_TypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_System {
        get {
            return this.qdetl_SystemField;
        }
        set {
            this.qdetl_SystemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Company {
        get {
            return this.qdetl_CompanyField;
        }
        set {
            this.qdetl_CompanyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Id {
        get {
            return this.qdetl_IdField;
        }
        set {
            this.qdetl_IdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Qdetl_Userid {
        get {
            return this.qdetl_UseridField;
        }
        set {
            this.qdetl_UseridField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="HTTP://SHADOW.CONSECO.COM/QSEARCH/QDETL")]
public partial class Qdetl_Area {
    
    private Qdetl_AreaQdetl_Input qdetl_InputField;
    
    private Qdetl_AreaQdetl_Msgs qdetl_MsgsField;
    
    private Qdetl_AreaQdetl_Output qdetl_OutputField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Qdetl_AreaQdetl_Input Qdetl_Input {
        get {
            return this.qdetl_InputField;
        }
        set {
            this.qdetl_InputField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Qdetl_AreaQdetl_Msgs Qdetl_Msgs {
        get {
            return this.qdetl_MsgsField;
        }
        set {
            this.qdetl_MsgsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public Qdetl_AreaQdetl_Output Qdetl_Output {
        get {
            return this.qdetl_OutputField;
        }
        set {
            this.qdetl_OutputField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void DODETLCompletedEventHandler(object sender, DODETLCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DODETLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DODETLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Qdetl_Area Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Qdetl_Area)(this.results[0]));
        }
    }
}
